/// Модель данных для эмодзи и их категорий
class EmojiCategory {
  final String id;
  final String name;
  final String icon;
  final List<String> emojis;

  const EmojiCategory({
    required this.id,
    required this.name,
    required this.icon,
    required this.emojis,
  });
}

/// Все доступные категории эмодзи с полным набором эмодзи
class EmojiData {
  static const List<EmojiCategory> categories = [
    // Смайлики и эмоции
    EmojiCategory(
      id: 'smileys',
      name: 'Смайлики',
      icon: '😀',
      emojis: [
        '😀', '😃', '😄', '😁', '😆', '😅', '🤣', '😂',
        '🙂', '🙃', '🫠', '😉', '😊', '😇', '🥰', '😍',
        '🤩', '😘', '😗', '☺️', '😚', '😙', '🥲', '😋',
        '😛', '😜', '🤪', '😝', '🤑', '🤗', '🤭',
        '🫣', '🤫', '🤔', '🤨', '😐', '😑', '🫡', '😮‍💨',
        '😶', '🫥', '😶‍🌫️', '😏', '😒', '🙄', '😬', '😮‍💨',
        '🤥', '😌', '😔', '😪', '🤤', '😴', '😷',
        '🤒', '🤕', '🤢', '🤮', '🤧', '🥵', '🥶', '🥴',
        '😵', '😵‍💫', '🤯', '🤠', '🥳', '🥸', '😎', '🤓',
        '🧐', '😕', '🫤', '😟', '🙁', '☹️', '😮', '😯',
        '😲', '😳', '🥺', '😦', '😧', '😨', '😰',
        '😥', '😢', '😭', '😱', '😖', '😣', '😞', '😓',
        '😩', '😫', '🥱', '😤', '😡', '😠', '🤬', '😈',
        '👿', '💀', '☠️', '💩', '🤡', '👹', '👺', '👻',
        '👽', '👾', '🤖', '😺', '😸', '😹', '😻', '😼',
        '😽', '🙀', '😿', '😾', '🙈', '🙉', '🙊',
        // ZWJ-последовательности смайликов
      ],
    ),

    // Люди и тела
    EmojiCategory(
      id: 'people',
      name: 'Люди',
      icon: '👤',
      emojis: [
        '👋', '🤚', '🖐️', '✋', '🖖', '👌', '🤌', '🤏',
        '✌️', '🤞', '🤘', '🤙', '👈', '👉', '👆', '🖕',
        '👇', '🫵', '👍', '👎', '👊', '✊', '🤛', '🤜',
        '👏', '🙌', '👐', '🤲', '🤝', '🙏', '✍️', '💅',
        '🤳', '💪', '🦾', '🦿', '🦵', '🦶', '👂', '🦻',
        '👃', '🧠', '🫀', '🫁', '🦷', '🦴', '👀', '👁️',
        '👄', '💋', '🩸',
      ],
    ),

    // Еда и напитки
    EmojiCategory(
      id: 'food',
      name: 'Еда',
      icon: '🍎',
      emojis: [
        '🍎', '🍐', '🍊', '🍋', '🍌', '🍉', '🍇', '🍓',
        '🫐', '🍈', '🍒', '🍑', '🥭', '🍍', '🥥', '🥝',
        '🍅', '🍆', '🥑', '🥦', '🥬', '🥒', '🌶️', '🫑',
        '🌽', '🥕', '🫒', '🧄', '🧅', '🥔', '🍠', '🥐',
        '🥖', '🫓', '🥨', '🥯', '🍞', '🥞', '🧇', '🧀',
        '🥚', '🍳', '🧈', '🥓', '🥩', '🍗', '🍖', '🌭',
        '🍔', '🍟', '🍕', '🫕', '🥙', '🌮', '🌯', '🫔',
        '🥗', '🥘', '🫙', '🍝', '🍜', '🍲', '🍛', '🍣',
        '🍱', '🥟', '🦪', '🍤', '🍙', '🍚', '🥡', '🍦',
        '🍧', '🍨', '🍩', '🍪', '🎂', '🍰', '🧁', '🥧',
        '🍫', '🍬', '🍭', '🍮', '🍯', '🍼', '🥛', '☕',
        '🫖', '🍵', '🧃', '🥤', '🧋', '🍶', '🍺', '🍻',
        '🥂', '🍷', '🥃', '🍸', '🍹', '🧉', '🧊', '🥢',
        '🍽️', '🍴', '🥄',
      ],
    ),

    // Животные и природа
    EmojiCategory(
      id: 'animals',
      name: 'Животные',
      icon: '🐶',
      emojis: [
        '🐶', '🐱', '🐭', '🐹', '🐰', '🦊', '🐻', '🐼',
        '🐨', '🐯', '🦁', '🐮', '🐷', '🐽', '🐸', '🐵',
        '🙈', '🙉', '🙊', '🐒', '🐔', '🐧', '🐦', '🐤',
        '🐣', '🐥', '🦆', '🦅', '🦉', '🦇', '🐺', '🐗',
        '🐴', '🦄', '🐝', '🐛', '🦋', '🐌', '🐞', '🐜',
        '🦗', '🕷️', '🦂', '🐢', '🐍', '🦎', '🦖', '🦕',
        '🐙', '🦑', '🦐', '🦞', '🦀', '🐡', '🐠', '🐟',
        '🐬', '🐳', '🐋', '🦈', '🐊', '🐅', '🐆', '🦓',
        '🦍', '🦧', '🐘', '🦛', '🦏', '🐪', '🐫', '🦒',
        '🦘', '🐃', '🐂', '🐄', '🐎', '🐖', '🐏', '🐑',
        '🦙', '🐐', '🦌', '🐕', '🐩', '🦮', '🐕‍🦺', '🐈',
        '🐈‍⬛', '🪶', '🐾', '🐉',
      ],
    ),

    // Растения и природа
    EmojiCategory(
      id: 'nature',
      name: 'Природа',
      icon: '🌸',
      emojis: [
        '💐', '🌸', '🌺', '🌻', '🌹', '🥀', '🌷', '🌼',
        '🌿', '🍀', '🍃', '🌾', '🌵', '🌲', '🌳', '🌴',
        '🌱', '☘️', '🍂', '🍁', '🍄', '🌰',
      ],
    ),

    // Активности
    EmojiCategory(
      id: 'activities',
      name: 'Активности',
      icon: '⚽',
      emojis: [
        '⚽', '🏀', '🏈', '⚾', '🥎', '🎾', '🏐', '🏉',
        '🥏', '🎱', '🪀', '🏓', '🏸', '🏒', '🏑', '🥍',
        '🏏', '🪃', '🥅', '⛳', '🪁', '🏹', '🎣', '🤿',
        '🥊', '🥋', '🎽', '🛹', '🛷', '⛸️', '🥌', '🎿',
        '⛷️', '🏂', '🪂', '🏋️', '🤸', '🤼', '🤽', '🤾',
        '🧘', '🏃', '🚶', '🧎', '🧍', '🤺', '🏇', '⛹️',
        '🏌️', '🏄', '🚣', '🏊', '⛹️‍♀️', '🏋️‍♀️', '🚴', '🚵',
        '🤹', '🎪', '🎭', '🩰', '🎨', '🎬', '🎤', '🎧',
        '🎼', '🎹', '🥁', '🪘', '🎷', '🎺', '🪗', '🎸',
        '🪕', '🎻', '🎲', '♠️', '♥️', '♦️', '♣️', '🃏',
        '🀄', '🎴', '🎯', '🎳', '🎮', '🕹️', '🎰',
      ],
    ),

    // Путешествия
    EmojiCategory(
      id: 'travel',
      name: 'Путешествия',
      icon: '✈️',
      emojis: [
        '🚗', '🚕', '🚙', '🚌', '🚎', '🏎️', '🚓', '🚑',
        '🚒', '🚐', '🚚', '🚛', '🚜', '🏍️', '🛵', '🚲',
        '🛴', '🛹', '🚏', '🛣️', '🛤️', '🛢️', '⛽', '🚨',
        '🚥', '🚦', '🛑', '🚧', '⚓', '⛵', '🛶', '🚤',
        '🛳️', '⛴️', '🛥️', '🚢', '✈️', '🛩️', '🛫', '🛬',
        '🪂', '💺', '🚁', '🚟', '🚠', '🚡', '🛤️', '🛸',
        '🚀', '🛸', '🌍', '🌎', '🌏', '🌐', '🗺️', '🗿',
        '🗽', '🗼', '🏰', '🏯', '🏟️', '🎡', '🎢', '🎠',
        '⛱️', '🏖️', '🏝️', '🏜️', '🌋', '⛰️', '🏔️', '🗻',
        '🏕️', '⛺', '🏠', '🏡', '🏘️', '🏙️', '🌆', '🌃',
        '🏙️', '🌉', '🌌',
      ],
    ),

    // Объекты
    EmojiCategory(
      id: 'objects',
      name: 'Объекты',
      icon: '💡',
      emojis: [
        '⌚', '📱', '📲', '💻', '⌨️', '🖥️', '🖨️', '🖱️',
        '🖲️', '🕹️', '🗜️', '💽', '💾', '💿', '📀', '📼',
        '📷', '📸', '📹', '🎥', '📽️', '🎞️', '📞', '☎️',
        '📟', '📠', '📺', '📻', '🎙️', '🎚️', '🎛️', '🧭',
        '⏱️', '⏲️', '⏰', '🕰️', '⌛', '⏳', '📡', '🔋',
        '🔌', '💡', '🔦', '🕯️', '🪔', '🧯', '🛢️', '💸',
        '💵', '💴', '💶', '💷', '💰', '💳', '💎', '⚖️',
        '🪜', '🧰', '🪛', '🔧', '🔨', '⚒️', '🛠️', '⛏️',
        '🔩', '⚙️', '🪚', '🔫', '🪃', '🏹', '🛡️', '🔪',
        '🗡️', '⚔️', '💣', '🪓', '⛏️', '⚒️', '🛠️', '🪚',
        '🔧', '🪛', '🧰', '🪜', '⚖️', '🧲', '🧪', '🧫',
        '🧬', '🔬', '🔭', '📡', '💉', '🩸', '💊', '🩹',
        '🩼', '🩺', '🩻', '🚪', '🪞', '🪟', '🛏️', '🛋️',
        '🪑', '🚽', '🪠', '🚿', '🛁', '🪤', '🪒', '🧴',
        '🧷', '🧹', '🧺', '🧻', '🪣', '🧼', '🫧', '🧽',
        '🧯', '🛒', '🚬', '⚰️', '🪦', '🏺',
      ],
    ),

    // Символы
    EmojiCategory(
      id: 'symbols',
      name: 'Символы',
      icon: '❤️',
      emojis: [
        '❤️', '🧡', '💛', '💚', '💙', '💜', '🖤', '🤍',
        '🤎', '💔', '❤️‍🔥', '❤️‍🩹', '💕', '💞', '💓', '💗',
        '💖', '💘', '💝', '💟', '☮️', '✝️', '☪️', '🕉️',
        '☸️', '✡️', '🔯', '🕎', '☯️', '☦️', '🛐', '⛎',
        '♈', '♉', '♊', '♋', '♌', '♍', '♎', '♏', '♐',
        '♑', '♒', '♓', '🆔', '⚛️', '🉑', '☢️', '☣️', '📴',
        '📳', '🈶', '🈚', '🈸', '🈺', '🈷️', '✴️', '🆚',
        '💮', '🉐', '㊙️', '㊗️', '🈴', '🈵', '🈹', '🈲',
        '🅰️', '🅱️', '🆎', '🆑', '🅾️', '🆘', '❌', '⭕',
        '🛑', '⛔', '📛', '🚫', '💯', '💢', '♨️', '🚷',
        '🚯', '🚳', '🚱', '🔞', '📵', '🚭', '❗', '❕',
        '❓', '❔', '‼️', '⁉️', '🔅', '🔆', '〽️', '⚠️',
        '🚸', '🔱', '⚜️', '🔰', '♻️', '✅', '❌', '💹',
        '💱', '💲', '⚕️', '🛡️', '⛎', '🚾',
      ],
    ),

    // Флаги
    EmojiCategory(
      id: 'flags',
      name: 'Флаги',
      icon: '🏁',
      emojis: [
        '🏁', '🚩', '🎌', '🏴', '🏳️', '🏳️‍🌈', '🏳️‍⚧️', '🏴‍☠️',
        // Флаги стран мира (все существующие)
        '🇦🇫', '🇦🇱', '🇦🇿', '🇦🇸', '🇦🇩', '🇦🇴', '🇦🇮', '🇦🇶', '🇦🇬', '🇦🇷', '🇦🇲', '🇦🇼', '🇦🇺', '🇦🇹', '🇦🇿', '🇧🇸', '🇧🇭', '🇧🇩', '🇧🇧', '🇧🇾', '🇧🇪', '🇧🇿', '🇧🇯', '🇧🇲', '🇧🇹', '🇧🇴', '🇧🇦', '🇧🇼', '🇧🇻', '🇧🇷', '🇮🇴', '🇻🇬', '🇧🇳', '🇧🇬', '🇧🇫', '🇧🇮', '🇧🇶', '🇰🇾', '🇨🇫', '🇹🇩', '🇨🇱', '🇨🇳', '🇨🇽', '🇨🇨', '🇨🇴', '🇰🇲', '🇨🇩', '🇨🇬', '🇨🇰', '🇨🇷', '🇭🇷', '🇨🇺', '🇨🇼', '🇨🇾', '🇨🇿', '🇨🇮', '🇩🇰', '🇩🇯', '🇩🇲', '🇩🇴', '🇪🇨', '🇪🇬', '🇸🇻', '🇬🇶', '🇪🇷', '🇪🇪', '🇸🇿', '🇪🇹', '🇫🇰', '🇫🇴', '🇫🇯', '🇫🇮', '🇫🇷', '🇬🇫', '🇵🇫', '🇹🇫', '🇬🇦', '🇬🇲', '🇬🇪', '🇩🇪', '🇬🇭', '🇬🇮', '🇬🇷', '🇬🇱', '🇬🇩', '🇬🇵', '🇬🇺', '🇬🇹', '🇬🇬', '🇬🇳', '🇬🇼', '🇬🇾', '🇭🇹', '🇭🇲', '🇭🇳', '🇭🇰', '🇭🇺', '🇮🇸', '🇮🇳', '🇮🇩', '🇮🇷', '🇮🇶', '🇮🇪', '🇮🇲', '🇮🇱', '🇮🇹', '🇯🇲', '🇯🇵', '🇯🇪', '🇯🇴', '🇰🇿', '🇰🇪', '🇰🇮', '🇽🇰', '🇰🇼', '🇰🇬', '🇱🇦', '🇱🇻', '🇱🇧', '🇱🇸', '🇱🇷', '🇱🇾', '🇱🇮', '🇱🇹', '🇱🇺', '🇲🇴', '🇲🇬', '🇲🇼', '🇲🇾', '🇲🇻', '🇲🇱', '🇲🇹', '🇲🇭', '🇲🇶', '🇲🇷', '🇲🇺', '🇾🇹', '🇲🇽', '🇫🇲', '🇲🇩', '🇲🇨', '🇲🇳', '🇲🇪', '🇲🇸', '🇲🇦', '🇲🇿', '🇲🇲', '🇳🇦', '🇳🇷', '🇳🇵', '🇳🇱', '🇳🇨', '🇳🇿', '🇳🇮', '🇳🇪', '🇳🇬', '🇳🇺', '🇳🇫', '🇰🇵', '🇲🇵', '🇳🇴', '🇴🇲', '🇵🇰', '🇵🇼', '🇵🇸', '🇵🇦', '🇵🇬', '🇵🇾', '🇵🇪', '🇵🇭', '🇵🇳', '🇵🇱', '🇵🇹', '🇵🇷', '🇶🇦', '🇷🇪', '🇷🇴', '🇷🇺', '🇷🇼', '🇼🇸', '🇸🇲', '🇸🇹', '🇸🇦', '🇸🇳', '🇷🇸', '🇸🇨', '🇸🇱', '🇸🇬', '🇸🇽', '🇸🇰', '🇸🇮', '🇸🇧', '🇸🇴', '🇿🇦', '🇬🇸', '🇰🇷', '🇸🇸', '🇪🇸', '🇱🇰', '🇧🇱', '🇸🇭', '🇰🇳', '🇱🇨', '🇲🇫', '🇵🇲', '🇻🇨', '🇸🇩', '🇸🇷', '🇸🇯', '🇸🇪', '🇨🇭', '🇸🇾', '🇹🇼', '🇹🇯', '🇹🇿', '🇹🇭', '🇹🇱', '🇹🇬', '🇹🇰', '🇹🇴', '🇹🇷', '🇹🇹', '🇹🇳', '🇹🇲', '🇹🇨', '🇹🇻', '🇺🇬', '🇺🇦', '🇦🇪', '🇬🇧', '🇺🇲', '🇺🇸', '🇺🇾', '🇺🇿', '🇻🇺', '🇻🇦', '🇻🇪', '🇻🇳', '🇻🇮', '🇼🇫', '🇪🇭', '🇾🇪', '🇿🇲', '🇿🇼'
      ],
    ),
  ];
  /// Словарь с названиями эмодзи для поиска на разных языках
  static const Map<String, List<String>> _emojiKeywords = {
    // Смайлики и эмоции - Основные
    '😀': ['смешной', 'улыбка', 'счастье', 'grinning face', 'sonriente', 'sourire', 'lächeln', 'sorriso', 'feliz'],
    '😃': ['смешной', 'улыбка', 'рот', 'grinning face with big eyes', 'sonriente grande', 'sourire grand', 'grinsendes Gesicht', 'sorriso grande', 'feliz grande'],
    '😄': ['смешной', 'улыбка', 'глаза', 'grinning face with smiling eyes', 'sonriente ojos', 'sourire yeux', 'lächelndes Gesicht', 'sorriso occhi', 'feliz ojos'],
    '😁': ['смешной', 'улыбка', 'сияние', 'beaming face with smiling eyes', 'radiante', 'rayonnant', 'strahlendes Gesicht', 'raggiante', 'radiante'],
    '😆': ['смешной', 'улыбка', 'смех', 'grinning squinting face', 'riendo', 'riant', 'lachendes Gesicht', 'ridendo', 'riendo'],
    '😅': ['нервный', 'пот', 'улыбка', 'grinning face with sweat', 'sudor nervioso', 'sueur nerveuse', 'schwitzendes Gesicht', 'sudore nervoso', 'sudor nervioso'],
    '🤣': ['смех', 'кататься', 'смеяться', 'rolling on the floor laughing', 'riendo suelo', 'riant par terre', 'lachend am Boden', 'ridendo per terra', 'riendo suelo'],
    '😂': ['смех', 'слезы', 'face with tears of joy', 'lagrimas risa', 'larmes joie', 'Tränen Freude', 'lacrime gioia', 'lagrimas alegria'],
    '🙂': ['улыбка', 'слегка', 'slightly smiling face', 'sonrisa leve', 'sourire léger', 'leicht lächelnd', 'sorriso lieve', 'sonrisa leve'],
    '🙃': ['перевернутый', 'upsidedown face', 'cara invertida', 'visage renversé', 'umgedrehtes Gesicht', 'faccia capovolta', 'cara invertida'],
    '😉': ['подмигивать', 'winking face', 'guiño', 'clin d\'œil', 'zwinkerndes Gesicht', 'occhiolino', 'guiño'],
    '😊': ['улыбка', 'глаза', 'smiling face with smiling eyes', 'sonrisa ojos', 'sourire yeux', 'lächelndes Gesicht Augen', 'sorriso occhi', 'sonrisa ojos'],
    '😇': ['ангел', 'halo', 'smiling face with halo', 'ángel', 'ange', 'Engel', 'angelo', 'angel'],
    '🥰': ['любовь', 'сердца', 'smiling face with hearts', 'amor corazones', 'amour cœurs', 'Liebe Herzen', 'amore cuori', 'amor corazones'],
    '😍': ['любовь', 'сердца', 'глаза', 'smiling face with heart-eyes', 'amor ojos corazones', 'amour yeux cœurs', 'Liebe Herz Augen', 'amore occhi cuori', 'amor ojos corazones'],
    '🤩': ['звезды', 'глаза', 'star-struck', 'estrellas ojos', 'étoiles yeux', 'Sterne Augen', 'stelle occhi', 'estrellas ojos'],
    '😘': ['поцелуй', 'air kiss', 'beso aire', 'baiser volant', 'Luftkuss', 'bacio volante', 'beso aire'],
    '😗': ['поцелуй', 'kissing face', 'beso', 'baiser', 'Kuss', 'bacio', 'beso'],
    '☺️': ['улыбка', 'smiling face', 'sonrisa', 'sourire', 'Lächeln', 'sorriso', 'sonrisa'],
    '😚': ['поцелуй', 'глаза', 'закрытые', 'kissing face with closed eyes', 'beso ojos cerrados', 'baiser yeux fermés', 'Kuss geschlossene Augen', 'bacio occhi chiusi', 'beso ojos cerrados'],
    '😙': ['поцелуй', 'улыбка', 'kissing face with smiling eyes', 'beso sonrisa', 'baiser sourire', 'Kuss lächelnde Augen', 'bacio sorriso', 'beso sonrisa'],
    '🥲': ['слеза', 'улыбка', 'smiling face with tear', 'sonrisa lagrima', 'sourire larme', 'Lächeln Träne', 'sorriso lacrima', 'sonrisa lagrima'],
    '😋': ['вкусный', 'язык', 'face savoring food', 'delicioso lengua', 'délicieux langue', 'leckeres Essen Gesicht', 'delizioso lingua', 'delicioso lengua'],
    '😛': ['язык', 'face with tongue', 'lengua', 'langue', 'Zunge', 'lingua', 'lengua'],
    '😜': ['подмигивать', 'язык', 'winking face with tongue', 'guiño lengua', 'clin d\'œil langue', 'zwinkernde Zunge', 'occhiolino lingua', 'guiño lengua'],
    '🤪': ['сумасшедший', 'zany face', 'loco', 'fou', 'verrückt', 'pazzo', 'loco'],
    '😝': ['закрытые', 'глаза', 'язык', 'squinting face with tongue', 'ojos cerrados lengua', 'yeux fermés langue', 'geschlossene Augen Zunge', 'occhi chiusi lingua', 'ojos cerrados lengua'],
    '🤑': ['деньги', 'money-mouth face', 'dinero boca', 'argent bouche', 'Geld Mund', 'soldi bocca', 'dinero boca'],
    '🤗': ['объятия', 'hugging face', 'abrazo', 'câlin', 'Umarmung', 'abbraccio', 'abrazo'],
    '🤭': ['рот', 'рука', 'face with hand over mouth', 'mano boca', 'main bouche', 'Hand Mund', 'mano bocca', 'mano boca'],
    '🫣': ['глаз', 'пальцы', 'face with peeking eye', 'ojo dedos', 'œil doigts', 'Auge Finger', 'occhio dita', 'ojo dedos'],
    '🤫': ['тихо', 'shushing face', 'silencio', 'chut', 'psst', 'silenzio', 'silencio'],
    '🤔': ['думать', 'thinking face', 'pensando', 'pensant', 'denkend', 'pensando', 'pensando'],
    '🤨': ['бровь', 'face with raised eyebrow', 'ceja levantada', 'sourcil levé', 'Augenbraue hoch', 'sopracciglio alzato', 'ceja levantada'],
    '😐': ['нейтральный', 'neutral face', 'neutral', 'neutre', 'neutral', 'neutro', 'neutral'],
    '😑': ['выражение', 'expressionless face', 'inexpresivo', 'sans expression', 'ausdruckslos', 'inespressivo', 'inexpresivo'],
    '😶': ['рот', 'закрытый', 'face without mouth', 'boca cerrada', 'bouche fermée', 'Mund zu', 'bocca chiusa', 'boca cerrada'],
    '🫥': ['пунктир', 'dotted line face', 'linea punteada', 'pointillés', 'gepunktet', 'linea punteggiata', 'linea punteada'],
    '😶‍🌫️': ['туман', 'face in clouds', 'cara nubes', 'visage nuages', 'Gesicht Wolken', 'faccia nuvole', 'cara nubes'],
    '😏': ['ухмылка', 'smirking face', 'sonrisa burlona', 'sourire narquois', 'schmunzelndes Gesicht', 'sorriso furbo', 'sonrisa burlona'],
    '😒': ['недовольный', 'unamused face', 'descontento', 'mécontent', 'unzufrieden', 'scontento', 'descontento'],
    '🙄': ['глаза', 'закатывать', 'face with rolling eyes', 'ojos rodando', 'yeux roulants', 'Augen rollen', 'occhi rotanti', 'ojos rodando'],
    '😬': ['гримаса', 'grimacing face', 'mueca', 'grimace', 'Grimasse', 'smorfia', 'mueca'],
    '🤥': ['ложь', 'lying face', 'mentira', 'mensonge', 'lügend', 'bugia', 'mentira'],
    '😌': ['облегчение', 'relieved face', 'aliviado', 'soulagé', 'erleichtert', 'sollievo', 'aliviado'],
    '😔': ['разочарование', 'pensive face', 'pensativo', 'pensif', 'nachdenklich', 'pensieroso', 'pensativo'],
    '😪': ['сонный', 'sleepy face', 'somnoliento', 'somnolent', 'schläfrig', 'sonnolento', 'somnoliento'],
    '🤤': ['слюни', 'drooling face', 'baboso', 'bavant', 'sabbernd', 'sbavante', 'baboso'],
    '😴': ['спать', 'sleeping face', 'durmiendo', 'dormant', 'schlafend', 'dormendo', 'durmiendo'],
    '😷': ['маска', 'face with medical mask', 'mascarilla', 'masque médical', 'medizinische Maske', 'mascherina', 'mascarilla'],
    '🤒': ['больной', 'face with thermometer', 'enfermo termometro', 'malade thermomètre', 'krank Thermometer', 'malato termometro', 'enfermo termometro'],
    '🤕': ['бинт', 'face with head-bandage', 'vendaje cabeza', 'pansement tête', 'Kopfverband', 'bendaggio testa', 'vendaje cabeza'],
    '🤢': ['тошнота', 'nauseated face', 'náuseas', 'nauséeux', 'übel', 'nauseato', 'náuseas'],
    '🤮': ['рвота', 'face vomiting', 'vomitando', 'vomissant', 'erbrechend', 'vomitando', 'vomitando'],
    '🤧': ['чихать', 'sneezing face', 'estornudando', 'éternuant', 'niesend', 'starnutendo', 'estornudando'],
    '🥵': ['жарко', 'hot face', 'calor', 'chaud', 'heiß', 'caldo', 'calor'],
    '🥶': ['холодно', 'cold face', 'frío', 'froid', 'kalt', 'freddo', 'frío'],
    '🥴': ['опьянение', 'woozy face', 'mareado', 'étourdi', 'schwindelig', 'stordito', 'mareado'],
    '😵': ['головокружение', 'dizzy face', 'mareado', 'étourdi', 'schwindelig', 'vertigini', 'mareado'],
    '🤯': ['взрыв', 'exploding head', 'explosion cabeza', 'explosion tête', 'explodierender Kopf', 'esplosione testa', 'explosion cabeza'],
    '🤠': ['ковбой', 'cowboy hat face', 'vaquero', 'cowboy', 'Cowboy', 'cowboy', 'vaquero'],
    '🥳': ['праздник', 'partying face', 'fiesta', 'fête', 'Party', 'festa', 'fiesta'],
    '🥸': ['маскировка', 'disguised face', 'disfrazado', 'déguisé', 'verkleidet', 'travestito', 'disfrazado'],
    '😎': ['очки', 'smiling face with sunglasses', 'gafas sol', 'lunettes soleil', 'Sonnenbrille', 'occhiali sole', 'gafas sol'],
    '🤓': ['умник', 'nerd face', 'nerd', 'intello', 'Nerd', 'nerd', 'nerd'],
    '🧐': ['очки', 'face with monocle', 'monoculo', 'monocle', 'Monokel', 'monocolo', 'monoculo'],

    // Люди и части тела
    '👋': ['привет', 'махать', 'waving hand', 'saludo', 'salut', 'winken', 'saluto', 'saludo'],
    '🤚': ['рука', 'поднятая', 'raised back of hand', 'dorso mano', 'dos main', 'Handrücken', 'dorso mano', 'dorso mano'],
    '🖐️': ['пальцы', 'раскрытые', 'hand with fingers splayed', 'dedos abiertos', 'doigts écartés', 'gespreizte Finger', 'dita aperte', 'dedos abiertos'],
    '✋': ['стоп', 'рука', 'raised hand', 'mano alzada', 'main levée', 'erhobene Hand', 'mano alzata', 'mano alzada'],
    '🖖': ['вулканский', 'спок', 'vulcan salute', 'saludo vulcan', 'salut vulcain', 'Vulkanier Gruß', 'saluto vulcaniano', 'saludo vulcan'],
    '👌': ['ок', 'о\'кей', 'OK hand', 'mano OK', 'main OK', 'OK Hand', 'mano OK', 'mano OK'],
    '🤌': ['щепотка', 'pinched fingers', 'dedos pellizcados', 'doigts pincés', 'zusammengedrückte Finger', 'dita pizzicate', 'dedos pellizcados'],
    '🤏': ['мало', 'pinching hand', 'mano pellizcando', 'main pinçant', 'kneifende Hand', 'mano pizzicando', 'mano pellizcando'],
    '✌️': ['мир', 'victory hand', 'mano victoria', 'main victoire', 'Victory Hand', 'mano vittoria', 'mano victoria'],
    '🤞': ['удача', 'crossed fingers', 'dedos cruzados', 'doigts croisés', 'gekreuzte Finger', 'dita incrociate', 'dedos cruzados'],
    '🤘': ['рок', 'sign of the horns', 'cuernos', 'cornes', 'Teufelsgruß', 'corna', 'cuernos'],
    '🤙': ['позвони', 'call me hand', 'llamame', 'appelle-moi', 'ruf mich an', 'chiamami', 'llamame'],
    '👈': ['влево', 'backhand index pointing left', 'apuntando izquierda', 'pointant gauche', 'nach links zeigend', 'indicando sinistra', 'apuntando izquierda'],
    '👉': ['вправо', 'backhand index pointing right', 'apuntando derecha', 'pointant droite', 'nach rechts zeigend', 'indicando destra', 'apuntando derecha'],
    '👆': ['вверх', 'backhand index pointing up', 'apuntando arriba', 'pointant haut', 'nach oben zeigend', 'indicando su', 'apuntando arriba'],
    '🖕': ['средний', 'middle finger', 'dedo medio', 'doigt d\'honneur', 'Mittelfinger', 'dito medio', 'dedo medio'],
    '👇': ['вниз', 'backhand index pointing down', 'apuntando abajo', 'pointant bas', 'nach unten zeigend', 'indicando giù', 'apuntando abajo'],
    '🫵': ['ты', 'index pointing at the viewer', 'apuntando ti', 'pointant vers toi', 'auf dich zeigend', 'indicando te', 'apuntando ti'],
    '👍': ['лайк', 'thumbs up', 'pulgar arriba', 'pouce haut', 'Daumen hoch', 'pollice su', 'pulgar arriba'],
    '👎': ['дизлайк', 'thumbs down', 'pulgar abajo', 'pouce bas', 'Daumen runter', 'pollice giù', 'pulgar abajo'],
    '👊': ['кулак', 'oncoming fist', 'puño', 'poing', 'Faust', 'pugno', 'puño'],
    '✊': ['поднятый кулак', 'raised fist', 'puño alzado', 'poing levé', 'erhobene Faust', 'pugno alzato', 'puño alzado'],
    '🤛': ['кулак слева', 'left-facing fist', 'puño izquierda', 'poing gauche', 'Faust links', 'pugno sinistro', 'puño izquierda'],
    '🤜': ['кулак справа', 'right-facing fist', 'puño derecha', 'poing droite', 'Faust rechts', 'pugno destro', 'puño derecha'],
    '👏': ['аплодисменты', 'clapping hands', 'aplaudiendo', 'applaudissant', 'klatschend', 'applaudendo', 'aplaudiendo'],
    '🙌': ['ура', 'raising hands', 'manos arriba', 'mains levées', 'Hände hoch', 'mani alzate', 'manos arriba'],
    '👐': ['открытые руки', 'open hands', 'manos abiertas', 'mains ouvertes', 'offene Hände', 'mani aperte', 'manos abiertas'],
    '🤲': ['ладони', 'palms up together', 'palmas juntas', 'paumes jointes', 'Handflächen zusammen', 'palmi unite', 'palmas juntas'],
    '🤝': ['рукопожатие', 'handshake', 'apretón manos', 'poignée de main', 'Händedruck', 'stretta mano', 'apretón manos'],
    '🙏': ['молитва', 'folded hands', 'manos plegadas', 'mains jointes', 'gefaltete Hände', 'mani giunte', 'manos plegadas'],
    '✍️': ['писать', 'writing hand', 'mano escribiendo', 'main écrivant', 'schreibende Hand', 'mano scrivente', 'mano escribiendo'],
    '💅': ['маникюр', 'nail polish', 'pintauñas', 'vernis ongles', 'Nagellack', 'smalto unghie', 'pintauñas'],
    '🤳': ['селфи', 'selfie', 'selfie', 'selfie', 'Selfie', 'selfie', 'selfie'],
    '💪': ['бицепс', 'flexed biceps', 'bíceps', 'biceps', 'Bizeps', 'bicipiti', 'bíceps'],
    '🦾': ['протез рука', 'mechanical arm', 'brazo mecánico', 'bras mécanique', 'mechanischer Arm', 'braccio meccanico', 'brazo mecánico'],
    '🦿': ['протез нога', 'mechanical leg', 'pierna mecánica', 'jambe mécanique', 'mechanisches Bein', 'gamba meccanica', 'pierna mecánica'],
    '🦵': ['нога', 'leg', 'pierna', 'jambe', 'Bein', 'gamba', 'pierna'],
    '🦶': ['ступня', 'foot', 'pie', 'pied', 'Fuß', 'piede', 'pie'],
    '👂': ['ухо', 'ear', 'oreja', 'oreille', 'Ohr', 'orecchio', 'oreja'],
    '🦻': ['слуховой аппарат', 'ear with hearing aid', 'oreja audífono', 'oreille appareil auditif', 'Ohr Hörgerät', 'orecchio apparecchio acustico', 'oreja audífono'],
    '👃': ['нос', 'nose', 'nariz', 'nez', 'Nase', 'naso', 'nariz'],
    '🧠': ['мозг', 'brain', 'cerebro', 'cerveau', 'Gehirn', 'cervello', 'cerebro'],
    '🫀': ['сердце анатомическое', 'anatomical heart', 'corazón anatómico', 'cœur anatomique', 'anatomisches Herz', 'cuore anatomico', 'corazón anatómico'],
    '🫁': ['легкие', 'lungs', 'pulmones', 'poumons', 'Lunge', 'polmoni', 'pulmones'],
    '🦷': ['зуб', 'tooth', 'diente', 'dent', 'Zahn', 'dente', 'diente'],
    '🦴': ['кость', 'bone', 'hueso', 'os', 'Knochen', 'osso', 'osso'],
    '👀': ['глаза', 'eyes', 'ojos', 'yeux', 'Augen', 'occhi', 'ojos'],
    '👁️': ['глаз', 'eye', 'ojo', 'œil', 'Auge', 'occhio', 'ojo'],
    '👄': ['рот', 'mouth', 'boca', 'bouche', 'Mund', 'bocca', 'boca'],
    '💋': ['поцелуй след', 'kiss mark', 'beso marca', 'marque baiser', 'Kussabdruck', 'impronta bacio', 'beso marca'],
    '🩸': ['кровь', 'drop of blood', 'gota sangre', 'goutte sang', 'Blutstropfen', 'goccia sangue', 'gota sangre'],

    // Еда и напитки
    '🍎': ['яблоко', 'apple', 'manzana', 'pomme', 'Apfel', 'mela', 'maçã'],
    '🍐': ['груша', 'pear', 'pera', 'poire', 'Birne', 'pera', 'pera'],
    '🍊': ['апельсин', 'orange', 'naranja', 'orange', 'Orange', 'arancia', 'laranja'],
    '🍋': ['лимон', 'lemon', 'limón', 'citron', 'Zitrone', 'limone', 'limão'],
    '🍌': ['банан', 'banana', 'plátano', 'banane', 'Banane', 'banana', 'banana'],
    '🍉': ['арбуз', 'watermelon', 'sandía', 'pastèque', 'Wassermelone', 'anguria', 'melancia'],
    '🍇': ['виноград', 'grapes', 'uvas', 'raisin', 'Trauben', 'uva', 'uvas'],
    '🍓': ['клубника', 'strawberry', 'fresa', 'fraise', 'Erdbeere', 'fragola', 'morango'],
    '🫐': ['черника', 'blueberries', 'arándanos', 'myrtilles', 'Blaubeeren', 'mirtilli', 'mirtilos'],
    '🍈': ['дыня', 'melon', 'melón', 'melon', 'Melone', 'melone', 'melão'],
    '🍒': ['вишня', 'cherries', 'cerezas', 'cerises', 'Kirschen', 'ciliegie', 'cerejas'],
    '🍑': ['персик', 'peach', 'durazno', 'pêche', 'Pfirsich', 'pesca', 'pêssego'],
    '🥭': ['манго', 'mango', 'mango', 'mangue', 'Mango', 'mango', 'manga'],
    '🍍': ['ананас', 'pineapple', 'piña', 'ananas', 'Ananas', 'ananas', 'abacaxi'],
    '🥥': ['кокос', 'coconut', 'coco', 'noix de coco', 'Kokosnuss', 'cocco', 'coco'],
    '🥝': ['киви', 'kiwi fruit', 'kiwi', 'kiwi', 'Kiwi', 'kiwi', 'kiwi'],
    '🍅': ['помидор', 'tomato', 'tomate', 'tomate', 'Tomate', 'pomodoro', 'tomate'],
    '🍆': ['баклажан', 'eggplant', 'berenjena', 'aubergine', 'Aubergine', 'melanzana', 'berinjela'],
    '🥑': ['авокадо', 'avocado', 'aguacate', 'avocat', 'Avocado', 'avocado', 'abacate'],
    '🥦': ['брокколи', 'broccoli', 'brócoli', 'brocoli', 'Brokkoli', 'broccoli', 'brócolis'],
    '🥬': ['зелень', 'leafy green', 'verdura hoja', 'légume vert', 'Blattgemüse', 'verdura foglia', 'verdura folha'],
    '🥒': ['огурец', 'cucumber', 'pepino', 'concombre', 'Gurke', 'cetriolo', 'pepino'],
    '🌶️': ['перец', 'hot pepper', 'pimiento picante', 'piment', 'Paprika', 'peperoncino', 'pimenta'],
    '🫑': ['болгарский', 'bell pepper', 'pimiento', 'poivron', 'Paprika', 'peperone', 'pimentão'],
    '🌽': ['кукуруза', 'ear of corn', 'maíz', 'maïs', 'Mais', 'mais', 'milho'],
    '🥕': ['морковь', 'carrot', 'zanahoria', 'carotte', 'Karotte', 'carota', 'cenoura'],
    '🫒': ['оливки', 'olive', 'aceituna', 'olive', 'Olive', 'oliva', 'azeitona'],
    '🧄': ['чеснок', 'garlic', 'ajo', 'ail', 'Knoblauch', 'aglio', 'alho'],
    '🧅': ['лук', 'onion', 'cebolla', 'oignon', 'Zwiebel', 'cipolla', 'cebola'],
    '🥔': ['картофель', 'potato', 'patata', 'pomme de terre', 'Kartoffel', 'patata', 'batata'],
    '🍠': ['батат', 'roasted sweet potato', 'camote', 'patate douce', 'Süßkartoffel', 'patata dolce', 'batata doce'],
    '🥐': ['круассан', 'croissant', 'cruasán', 'croissant', 'Croissant', 'croissant', 'croissant'],
    '🥖': ['багет', 'baguette bread', 'baguette', 'baguette', 'Baguette', 'baguette', 'baguete'],
    '🫓': ['лепешка', 'flatbread', 'pan plano', 'pain plat', 'Fladenbrot', 'pane piatto', 'pão plano'],
    '🥨': ['крендель', 'pretzel', 'pretzel', 'bretzel', 'Brezel', 'pretzel', 'pretzel'],
    '🥯': ['бейгл', 'bagel', 'bagel', 'bagel', 'Bagel', 'bagel', 'bagel'],
    '🍞': ['хлеб', 'bread', 'pan', 'pain', 'Brot', 'pane', 'pão'],
    '🥞': ['блинчики', 'pancakes', 'tortitas', 'crêpes', 'Pfannkuchen', 'pancake', 'panquecas'],
    '🧇': ['вафли', 'waffles', 'gofres', 'gaufres', 'Waffeln', 'cialde', 'waffles'],
    '🧀': ['сыр', 'cheese wedge', 'queso', 'fromage', 'Käse', 'formaggio', 'queijo'],
    '🥚': ['яйцо', 'egg', 'huevo', 'œuf', 'Ei', 'uovo', 'ovo'],
    '🍳': ['готовка', 'cooking', 'cocina', 'cuisine', 'Kochen', 'cucina', 'cozinha'],
    '🧈': ['масло', 'butter', 'mantequilla', 'beurre', 'Butter', 'burro', 'manteiga'],
    '🥓': ['бекон', 'bacon', 'tocino', 'bacon', 'Bacon', 'bacon', 'bacon'],
    '🥩': ['мясо', 'cut of meat', 'carne', 'viande', 'Fleisch', 'carne', 'carne'],
    '🍗': ['курица', 'poultry leg', 'pierna pollo', 'cuisse poulet', 'Hähnchenkeule', 'coscia pollo', 'coxa frango'],
    '🍖': ['кость с мясом', 'meat on bone', 'carne hueso', 'viande os', 'Fleisch Knochen', 'carne osso', 'carne osso'],
    '🌭': ['хот-дог', 'hot dog', 'perrito caliente', 'hot-dog', 'Hot Dog', 'hot dog', 'cachorro quente'],
    '🍔': ['бургер', 'hamburger', 'hamburguesa', 'hamburger', 'Hamburger', 'hamburger', 'hambúrguer'],
    '🍟': ['картошка фри', 'french fries', 'papas fritas', 'frites', 'Pommes', 'patatine fritte', 'batatas fritas'],
    '🍕': ['пицца', 'pizza', 'pizza', 'pizza', 'Pizza', 'pizza', 'pizza'],
    '🫕': ['фондю', 'fondue', 'fondue', 'fondue', 'Fondue', 'fonduta', 'fondue'],
    '🥙': ['шаурма', 'stuffed flatbread', 'shawarma', 'shawarma', 'Shawarma', 'shawarma', 'shawarma'],
    '🌮': ['такос', 'taco', 'taco', 'taco', 'Taco', 'taco', 'taco'],
    '🌯': ['буррито', 'burrito', 'burrito', 'burrito', 'Burrito', 'burrito', 'burrito'],
    '🫔': ['тамале', 'tamale', 'tamal', 'tamal', 'Tamale', 'tamale', 'tamal'],
    '🥗': ['салат', 'green salad', 'ensalada verde', 'salade verte', 'grüner Salat', 'insalata verde', 'salada verde'],
    '🥘': ['паэлья', 'shallow pan of food', 'paella', 'paella', 'Paella', 'paella', 'paella'],
    '🫙': ['банка', 'jar', 'tarro', 'pot', 'Glas', 'barattolo', 'pote'],
    '🍝': ['спагетти', 'spaghetti', 'espaguetis', 'spaghetti', 'Spaghetti', 'spaghetti', 'espaguete'],
    '🍜': ['лапша', 'steaming bowl', 'sopa humeante', 'bol fumant', 'dampfende Schüssel', 'ciotola fumante', 'tigela fumegante'],
    '🍲': ['суп', 'pot of food', 'olla comida', 'marmite nourriture', 'Topf Essen', 'pentola cibo', 'panela comida'],
    '🍛': ['карри', 'curry rice', 'arroz curry', 'riz curry', 'Curry Reis', 'riso curry', 'arroz curry'],
    '🍣': ['суши', 'sushi', 'sushi', 'sushi', 'Sushi', 'sushi', 'sushi'],
    '🍱': ['бенто', 'bento box', 'caja bento', 'boîte bento', 'Bento Box', 'bento box', 'caixa bento'],
    '🥟': ['пельмени', 'dumpling', 'dumpling', 'raviolis', 'Teigtaschen', 'ravioli', 'bolinho'],
    '🦪': ['устрица', 'oyster', 'ostra', 'huître', 'Auster', 'ostrica', 'ostra'],
    '🍤': ['креветка', 'fried shrimp', 'camarón frito', 'crevette frite', 'frittierte Garnele', 'gamberetto fritto', 'camarão frito'],
    '🍙': ['онигири', 'rice ball', 'bola arroz', 'boule riz', 'Reisball', 'palla riso', 'bola arroz'],
    '🍚': ['рис', 'cooked rice', 'arroz cocido', 'riz cuit', 'gekochter Reis', 'riso cotto', 'arroz cozido'],
    '🥡': ['еда навынос', 'takeout box', 'caja para llevar', 'boîte à emporter', 'Essen zum Mitnehmen', 'confezione da asporto', 'caixa para viagem'],
    '🍦': ['мороженое', 'soft ice cream', 'helado suave', 'glace douce', 'weiches Eis', 'gelato morbido', 'sorvete macio'],
    '🍧': ['фруктовый лед', 'shaved ice', 'hielo raspado', 'glace pilée', 'rasiertes Eis', 'ghiaccio tritato', 'gelo raspado'],
    '🍨': ['мороженое в чашке', 'ice cream', 'helado', 'glace', 'Eiscreme', 'gelato', 'sorvete'],
    '🍩': ['пончик', 'doughnut', 'dona', 'beignet', 'Donut', 'ciambella', 'rosquinha'],
    '🍪': ['печенье', 'cookie', 'galleta', 'biscuit', 'Keks', 'biscotto', 'biscoito'],
    '🎂': ['торт', 'birthday cake', 'pastel cumpleaños', 'gâteau anniversaire', 'Geburtstagskuchen', 'torta compleanno', 'bolo aniversário'],
    '🍰': ['пирог', 'shortcake', 'tarta', 'gâteau', 'Kuchen', 'torta', 'bolo'],
    '🧁': ['капкейк', 'cupcake', 'magdalena', 'cupcake', 'Cupcake', 'cupcake', 'cupcake'],
    '🥧': ['пирог', 'pie', 'tarta', 'tarte', 'Kuchen', 'torta', 'torta'],
    '🍫': ['шоколад', 'chocolate bar', 'barra chocolate', 'barre chocolat', 'Schokolade', 'cioccolato', 'chocolate'],
    '🍬': ['конфета', 'candy', 'caramelo', 'bonbon', 'Süßigkeit', 'caramella', 'doce'],
    '🍭': ['леденец', 'lollipop', 'piruleta', 'sucette', 'Lollis', 'lecca lecca', 'pirulito'],
    '🍮': ['пудинг', 'custard', 'flan', 'crème', 'Pudding', 'budino', 'pudim'],
    '🍯': ['мед', 'honey pot', 'miel', 'miel', 'Honig', 'miele', 'mel'],
    '🍼': ['бутылочка', 'baby bottle', 'biberón', 'biberon', 'Babyflasche', 'biberon', 'mamadeira'],
    '🥛': ['молоко', 'glass of milk', 'vaso leche', 'verre lait', 'Glas Milch', 'bicchiere latte', 'copo leite'],
    '☕': ['кофе', 'hot beverage', 'bebida caliente', 'boisson chaude', 'heißes Getränk', 'bevanda calda', 'bebida quente'],
    '🫖': ['чайник', 'teapot', 'tetera', 'théière', 'Teekanne', 'teiera', 'bule'],
    '🍵': ['чай', 'teacup without handle', 'taza té', 'tasse thé', 'Teetasse', 'tazza tè', 'xícara chá'],
    '🧃': ['сок', 'beverage box', 'caja bebida', 'boîte boisson', 'Getränkekarton', 'bevanda scatola', 'caixa bebida'],
    '🥤': ['кофе навынос', 'cup with straw', 'vaso pajita', 'gobelet paille', 'Becher Strohhalm', 'bicchiere cannuccia', 'copo canudo'],
    '🧋': ['баббл ти', 'bubble tea', 'té burbujas', 'thé bulles', 'Bubble Tea', 'bubble tea', 'chá bolha'],
    '🍶': ['саке', 'sake', 'sake', 'saké', 'Sake', 'sakè', 'saquê'],
    '🍺': ['пиво', 'beer mug', 'jarra cerveza', 'chope bière', 'Bierkrug', 'boccale birra', 'caneca cerveja'],
    '🍻': ['пиво тост', 'clinking beer mugs', 'cervezas brindis', 'chopes trinquant', 'anstößende Bierkrüge', 'boccali birra brindisi', 'canecas cerveja brindando'],
    '🥂': ['шампанское', 'clinking glasses', 'copas brindis', 'verres trinquant', 'anstößende Gläser', 'bicchieri brindisi', 'taças brindando'],
    '🍷': ['вино', 'wine glass', 'copa vino', 'verre vin', 'Weinglas', 'bicchiere vino', 'taça vinho'],
    '🥃': ['виски', 'tumbler glass', 'vaso whisky', 'verre whisky', 'Whiskyglas', 'bicchiere whisky', 'copo whisky'],
    '🍸': ['коктейль', 'cocktail glass', 'copa cóctel', 'verre cocktail', 'Cocktailglas', 'bicchiere cocktail', 'taça coquetel'],
    '🍹': ['тропический', 'tropical drink', 'bebida tropical', 'boisson tropicale', 'Tropengetränk', 'bevanda tropicale', 'bebida tropical'],
    '🧉': ['мате', 'mate', 'mate', 'maté', 'Mate', 'mate', 'mate'],
    '🧊': ['лед', 'ice', 'hielo', 'glace', 'Eis', 'ghiaccio', 'gelo'],
    '🥢': ['палочки', 'chopsticks', 'palillos', 'baguettes', 'Stäbchen', 'bacchette', 'hashi'],
    '🍽️': ['столовые приборы', 'fork and knife with plate', 'cubiertos plato', 'couverts assiette', 'Besteck Teller', 'posate piatto', 'talheres prato'],
    '🍴': ['вилка нож', 'fork and knife', 'tenedor cuchillo', 'fourchette couteau', 'Gabel Messer', 'forchetta coltello', 'garfo faca'],
    '🥄': ['ложка', 'spoon', 'cuchara', 'cuillère', 'Löffel', 'cucchiaio', 'colher'],

    // Животные и природа
    '🐶': ['собака', 'dog face', 'perro', 'chien', 'Hund', 'cane', 'cachorro'],
    '🐱': ['кот', 'cat face', 'gato', 'chat', 'Katze', 'gatto', 'gato'],
    '🐭': ['мышь', 'mouse face', 'ratón', 'souris', 'Maus', 'topo', 'rato'],
    '🐹': ['хомяк', 'hamster', 'hámster', 'hamster', 'Hamster', 'criceto', 'hamster'],
    '🐰': ['кролик', 'rabbit face', 'conejo', 'lapin', 'Kaninchen', 'coniglio', 'coelho'],
    '🦊': ['лиса', 'fox', 'zorro', 'renard', 'Fuchs', 'volpe', 'raposa'],
    '🐻': ['медведь', 'bear', 'oso', 'ours', 'Bär', 'orso', 'urso'],
    '🐼': ['панда', 'panda', 'panda', 'panda', 'Panda', 'panda', 'panda'],
    '🐨': ['коала', 'koala', 'koala', 'koala', 'Koala', 'koala', 'coala'],
    '🐯': ['тигр', 'tiger face', 'tigre', 'tigre', 'Tiger', 'tigre', 'tigre'],
    '🦁': ['лев', 'lion', 'león', 'lion', 'Löwe', 'leone', 'leão'],
    '🐮': ['корова', 'cow face', 'vaca', 'vache', 'Kuh', 'mucca', 'vaca'],
    '🐷': ['свинья', 'pig face', 'cerdo', 'cochon', 'Schwein', 'maiale', 'porco'],
    '🐽': ['пятачок', 'pig nose', 'hocico cerdo', 'groin cochon', 'Schweineschnauze', 'naso maiale', 'focinho porco'],
    '🐸': ['лягушка', 'frog', 'rana', 'grenouille', 'Frosch', 'rana', 'sapo'],
    '🐵': ['обезьяна', 'monkey face', 'mono', 'singe', 'Affe', 'scimmia', 'macaco'],
    '🙈': ['не вижу', 'see-no-evil monkey', 'no veo', 'pas voir', 'nicht sehen', 'non vedo', 'não vejo'],
    '🙉': ['не слышу', 'hear-no-evil monkey', 'no oigo', 'pas entendre', 'nicht hören', 'non sento', 'não ouço'],
    '🙊': ['не говорю', 'speak-no-evil monkey', 'no hablo', 'pas parler', 'nicht sprechen', 'non parlo', 'não falo'],
    '🐒': ['обезьяна', 'monkey', 'mono', 'singe', 'Affe', 'scimmia', 'macaco'],
    '🐔': ['курица', 'chicken', 'gallina', 'poule', 'Huhn', 'gallina', 'galinha'],
    '🐧': ['пингвин', 'penguin', 'pingüino', 'pingouin', 'Pinguin', 'pinguino', 'pinguim'],
    '🐦': ['птица', 'bird', 'pájaro', 'oiseau', 'Vogel', 'uccello', 'pássaro'],
    '🐤': ['цыпленок', 'baby chick', 'pollito', 'poussin', 'Küken', 'pulcino', 'pintinho'],
    '🐣': ['вылупление', 'hatching chick', 'pollito naciendo', 'poussin éclosion', 'schlüpfendes Küken', 'pulcino schiudendosi', 'pintinho chocando'],
    '🐥': ['цыпленок спереди', 'front-facing baby chick', 'pollito frente', 'poussin face', 'Küken von vorne', 'pulcino fronte', 'pintinho frente'],
    '🦆': ['утка', 'duck', 'pato', 'canard', 'Ente', 'anatra', 'pato'],
    '🦅': ['орел', 'eagle', 'águila', 'aigle', 'Adler', 'aquila', 'águia'],
    '🦉': ['сова', 'owl', 'búho', 'hibou', 'Eule', 'gufo', 'coruja'],
    '🦇': ['летучая мышь', 'bat', 'murciélago', 'chauve-souris', 'Fledermaus', 'pipistrello', 'morcego'],
    '🐺': ['волк', 'wolf', 'lobo', 'loup', 'Wolf', 'lupo', 'lobo'],
    '🐗': ['кабан', 'boar', 'jabalí', 'sanglier', 'Eber', 'cinghiale', 'javali'],
    '🐴': ['лошадь', 'horse face', 'caballo', 'cheval', 'Pferd', 'cavallo', 'cavalo'],
    '🦄': ['единорог', 'unicorn', 'unicornio', 'licorne', 'Einhorn', 'unicorno', 'unicórnio'],
    '🐝': ['пчела', 'honeybee', 'abeja', 'abeille', 'Biene', 'ape', 'abelha'],
    '🐛': ['гусеница', 'caterpillar', 'oruga', 'chenille', 'Raupe', 'bruco', 'lagarta'],
    '🦋': ['бабочка', 'butterfly', 'mariposa', 'papillon', 'Schmetterling', 'farfalla', 'borboleta'],
    '🐌': ['улитка', 'snail', 'caracol', 'escargot', 'Schnecke', 'lumaca', 'caracol'],
    '🐞': ['божья коровка', 'lady beetle', 'mariquita', 'coccinelle', 'Marienkäfer', 'coccinella', 'joaninha'],
    '🐜': ['муравей', 'ant', 'hormiga', 'fourmi', 'Ameise', 'formica', 'formiga'],
    '🦗': ['кузнечик', 'cricket', 'grillo', 'grillon', 'Grille', 'grillo', 'grilo'],
    '🕷️': ['паук', 'spider', 'araña', 'araignée', 'Spinne', 'ragno', 'aranha'],
    '🦂': ['скорпион', 'scorpion', 'escorpión', 'scorpion', 'Skorpion', 'scorpione', 'escorpião'],
    '🐢': ['черепаха', 'turtle', 'tortuga', 'tortue', 'Schildkröte', 'tartaruga', 'tartaruga'],
    '🐍': ['змея', 'snake', 'serpiente', 'serpent', 'Schlange', 'serpente', 'cobra'],
    '🦎': ['ящерица', 'lizard', 'lagarto', 'lézard', 'Eidechse', 'lucertola', 'lagarto'],
    '🦖': ['тираннозавр', 'T-Rex', 'tiranosaurio', 'tyrannosaure', 'T-Rex', 'tirannosauro', 'tiranosauro'],
    '🦕': ['бронтозавр', 'sauropod', 'saurópodo', 'sauropode', 'Sauropode', 'sauropode', 'sauropode'],
    '🐙': ['осьминог', 'octopus', 'pulpo', 'pieuvre', 'Oktopus', 'polpo', 'polvo'],
    '🦑': ['кальмар', 'squid', 'calamar', 'calmar', 'Tintenfisch', 'calamaro', 'lula'],
    '🦐': ['креветка', 'shrimp', 'camarón', 'crevette', 'Garnele', 'gamberetto', 'camarão'],
    '🦞': ['омар', 'lobster', 'langosta', 'homard', 'Hummer', 'aragosta', 'lagosta'],
    '🦀': ['краб', 'crab', 'cangrejo', 'crabe', 'Krabbe', 'granchio', 'caranguejo'],
    '🐡': ['рыба шар', 'blowfish', 'pez globo', 'poisson-globe', 'Kugelfisch', 'pesce palla', 'baiacu'],
    '🐠': ['тропическая рыба', 'tropical fish', 'pez tropical', 'poisson tropical', 'Tropenfisch', 'pesce tropicale', 'peixe tropical'],
    '🐟': ['рыба', 'fish', 'pez', 'poisson', 'Fisch', 'pesce', 'peixe'],
    '🐬': ['дельфин', 'dolphin', 'delfín', 'dauphin', 'Delfin', 'delfino', 'golfinho'],
    '🐳': ['кит', 'spouting whale', 'ballena', 'baleine', 'Wal', 'balena', 'baleia'],
    '🐋': ['кит', 'whale', 'ballena', 'baleine', 'Wal', 'balena', 'baleia'],
    '🦈': ['акула', 'shark', 'tiburón', 'requin', 'Hai', 'squalo', 'tubarão'],
    '🐊': ['крокодил', 'crocodile', 'cocodrilo', 'crocodile', 'Krokodil', 'coccodrillo', 'crocodilo'],
    '🐅': ['тигр', 'tiger', 'tigre', 'tigre', 'Tiger', 'tigre', 'tigre'],
    '🐆': ['леопард', 'leopard', 'leopardo', 'léopard', 'Leopard', 'leopardo', 'leopardo'],
    '🦓': ['зебра', 'zebra', 'cebra', 'zèbre', 'Zebra', 'zebra', 'zebra'],
    '🦍': ['горилла', 'gorilla', 'gorila', 'gorille', 'Gorilla', 'gorilla', 'gorila'],
    '🦧': ['орангутанг', 'orangutan', 'orangután', 'orang-outan', 'Orang-Utan', 'orangotango', 'orangotango'],
    '🐘': ['слон', 'elephant', 'elefante', 'éléphant', 'Elefant', 'elefante', 'elefante'],
    '🦛': ['бегемот', 'hippopotamus', 'hipopótamo', 'hippopotame', 'Nilpferd', 'ippopotamo', 'hipopótamo'],
    '🦏': ['носорог', 'rhinoceros', 'rinoceronte', 'rhinocéros', 'Nashorn', 'rinoceronte', 'rinoceronte'],
    '🐪': ['верблюд', 'camel', 'camello', 'chameau', 'Kamel', 'cammello', 'camelo'],
    '🐫': ['двугорбый верблюд', 'two-hump camel', 'camello dos jorobas', 'chameau deux bosses', 'Trampeltier', 'dromedario', 'camelo duas corcovas'],
    '🦒': ['жираф', 'giraffe', 'jirafa', 'girafe', 'Giraffe', 'giraffa', 'girafa'],
    '🦘': ['кенгуру', 'kangaroo', 'canguro', 'kangourou', 'Känguru', 'canguro', 'canguru'],
    '🐃': ['буйвол', 'water buffalo', 'búfalo agua', 'buffle eau', 'Wasserbüffel', 'bufalo d\'acqua', 'búfalo d\'água'],
    '🐂': ['бык', 'ox', 'buey', 'bœuf', 'Ochse', 'bue', 'boi'],
    '🐄': ['корова', 'cow', 'vaca', 'vache', 'Kuh', 'mucca', 'vaca'],
    '🐎': ['лошадь', 'horse', 'caballo', 'cheval', 'Pferd', 'cavallo', 'cavalo'],
    '🐖': ['свинья', 'pig', 'cerdo', 'cochon', 'Schwein', 'maiale', 'porco'],
    '🐏': ['баран', 'ram', 'carnero', 'bélier', 'Widder', 'ariete', 'carneiro'],
    '🐑': ['овца', 'ewe', 'oveja', 'brebis', 'Schaf', 'pecora', 'ovelha'],
    '🦙': ['лама', 'llama', 'llama', 'lama', 'Lama', 'lama', 'lhama'],
    '🐐': ['козел', 'goat', 'cabra', 'chèvre', 'Ziege', 'capra', 'cabra'],
    '🦌': ['олень', 'deer', 'ciervo', 'cerf', 'Hirsch', 'cervo', 'veado'],
    '🐕': ['собака', 'dog', 'perro', 'chien', 'Hund', 'cane', 'cachorro'],
    '🐩': ['пудель', 'poodle', 'caniche', 'caniche', 'Pudel', 'barboncino', 'poodle'],
    '🦮': ['поводырь', 'guide dog', 'perro guía', 'chien guide', 'Blindenhund', 'cane guida', 'cão guia'],
    '🐕‍🦺': ['служебная собака', 'service dog', 'perro servicio', 'chien service', 'Assistenzhund', 'cane servizio', 'cão serviço'],
    '🐈': ['кот', 'cat', 'gato', 'chat', 'Katze', 'gatto', 'gato'],
    '🐈‍⬛': ['черный кот', 'black cat', 'gato negro', 'chat noir', 'schwarze Katze', 'gatto nero', 'gato preto'],
    '🪶': ['перо', 'feather', 'pluma', 'plume', 'Feder', 'piuma', 'pena'],
    '🐾': ['следы лап', 'paw prints', 'huellas patas', 'empreintes pattes', 'Pfotenabdrücke', 'impronte zampe', 'pegadas patas'],
    '🐉': ['дракон', 'dragon', 'dragón', 'dragon', 'Drache', 'drago', 'dragão'],

    // Растения и природа
    '💐': ['букет', 'bouquet', 'ramo', 'bouquet', 'Blumenstrauß', 'mazzo', 'buquê'],
    '🌸': ['вишня цветок', 'cherry blossom', 'flor cerezo', 'fleur cerisier', 'Kirschblüte', 'fiore ciliegio', 'flor cerejeira'],
    '🌺': ['гибискус', 'hibiscus', 'hibisco', 'hibiscus', 'Hibiskus', 'ibisco', 'hibisco'],
    '🌻': ['подсолнух', 'sunflower', 'girasol', 'tournesol', 'Sonnenblume', 'girasole', 'girassol'],
    '🌹': ['роза', 'rose', 'rosa', 'rose', 'Rose', 'rosa', 'rosa'],
    '🥀': ['увядшая роза', 'wilted flower', 'rosa marchita', 'fleur fanée', 'verwelkte Blume', 'rosa appassita', 'rosa murcha'],
    '🌷': ['тюльпан', 'tulip', 'tulipán', 'tulipe', 'Tulpe', 'tulipano', 'tulipa'],
    '🌼': ['цветок', 'blossom', 'flor', 'fleur', 'Blüte', 'fiore', 'flor'],
    '🌿': ['трава', 'herb', 'hierba', 'herbe', 'Kraut', 'erba', 'erva'],
    '🍀': ['клевер', 'four leaf clover', 'trébol cuatro hojas', 'trèfle quatre feuilles', 'vierblättriges Kleeblatt', 'quadrifoglio', 'trevo quatro folhas'],
    '🍃': ['лист', 'leaf fluttering in wind', 'hoja viento', 'feuille vent', 'Blatt im Wind', 'foglia vento', 'folha vento'],
    '🌾': ['рис', 'sheaf of rice', 'espiga arroz', 'épi riz', 'Reisgarbe', 'covone riso', 'feixe arroz'],
    '🌵': ['кактус', 'cactus', 'cactus', 'cactus', 'Kaktus', 'cactus', 'cacto'],
    '🌲': ['ель', 'evergreen tree', 'árbol siempreverde', 'sapin', 'Tanne', 'abete', 'pinheiro'],
    '🌳': ['дерево', 'deciduous tree', 'árbol caducifolio', 'arbre', 'Laubbaum', 'albero', 'árvore'],
    '🌴': ['пальма', 'palm tree', 'palmera', 'palmier', 'Palme', 'palma', 'palmeira'],
    '🌱': ['росток', 'seedling', 'plántula', 'pousse', 'Keimling', 'piantina', 'muda'],
    '☘️': ['клевер', 'shamrock', 'trébol', 'trèfle', 'Kleeblatt', 'trifoglio', 'trevo'],
    '🍂': ['листья осень', 'fallen leaf', 'hoja caída', 'feuille tombée', 'gefallenes Blatt', 'foglia caduta', 'folha caída'],
    '🍁': ['кленовый лист', 'maple leaf', 'hoja arce', 'feuille érable', 'Ahornblatt', 'foglia acero', 'folha bordo'],
    '🍄': ['гриб', 'mushroom', 'hongo', 'champignon', 'Pilz', 'fungo', 'cogumelo'],
    '🌰': ['каштан', 'chestnut', 'castaña', 'châtaigne', 'Kastanie', 'castagna', 'castanha'],

    // Флаги
    '🏁': ['финиш', 'finish flag', 'bandera finish', 'drapeau arrivée', 'Zielflagge', 'bandiera traguardo', 'bandeira chegada'],
    '🚩': ['флаг', 'flag', 'bandera', 'drapeau', 'Flagge', 'bandiera', 'bandeira'],
    '🎌': ['перекрещенные флаги', 'crossed flags', 'banderas cruzadas', 'drapeaux croisés', 'gekreuzte Flaggen', 'bandiere incrociate', 'bandeiras cruzadas'],
    '🏴': ['черный флаг', 'black flag', 'bandera negra', 'drapeau noir', 'schwarze Flagge', 'bandiera nera', 'bandeira negra'],
    '🏳️': ['белый флаг', 'white flag', 'bandera blanca', 'drapeau blanc', 'weiße Flagge', 'bandiera bianca', 'bandeira branca'],
    '🏳️‍🌈': ['радуга флаг', 'rainbow flag', 'bandera arcoíris', 'drapeau arc-en-ciel', 'Regenbogenflagge', 'bandiera arcobaleno', 'bandeira arco-íris'],
    '🏳️‍⚧️': ['трансгендер флаг', 'transgender flag', 'bandera transgénero', 'drapeau transgenre', 'Transgenderflagge', 'bandiera transgender', 'bandeira transgênero'],
    '🏴‍☠️': ['пиратский флаг', 'pirate flag', 'bandera pirata', 'drapeau pirate', 'Piratenflagge', 'bandiera pirata', 'bandeira pirata'],

    // Флаги стран
    '🇦🇫': ['Афганистан', 'Afghanistan', 'Afganistán', 'Afghanistan', 'Afghanistan', 'Afghanistan', 'Afeganistão'],
    '🇦🇱': ['Албания', 'Albania', 'Albania', 'Albanie', 'Albanien', 'Albania', 'Albânia'],
    '🇩🇿': ['Алжир', 'Algeria', 'Argelia', 'Algérie', 'Algerien', 'Algeria', 'Argélia'],
    '🇦🇸': ['Американское Самоа', 'American Samoa', 'Samoa Americana', 'Samoa américaine', 'Amerikanisch-Samoa', 'Samoa Americana', 'Samoa Americana'],
    '🇦🇩': ['Андорра', 'Andorra', 'Andorra', 'Andorre', 'Andorra', 'Andorra', 'Andorra'],
    '🇦🇴': ['Ангола', 'Angola', 'Angola', 'Angola', 'Angola', 'Angola', 'Angola'],
    '🇦🇮': ['Ангилья', 'Anguilla', 'Anguila', 'Anguilla', 'Anguilla', 'Anguilla', 'Anguilla'],
    '🇦🇶': ['Антарктида', 'Antarctica', 'Antártida', 'Antarctique', 'Antarktis', 'Antartide', 'Antártida'],
    '🇦🇬': ['Антигуа и Барбуда', 'Antigua and Barbuda', 'Antigua y Barbuda', 'Antigua-et-Barbuda', 'Antigua und Barbuda', 'Antigua e Barbuda', 'Antígua e Barbuda'],
    '🇦🇷': ['Аргентина', 'Argentina', 'Argentina', 'Argentine', 'Argentinien', 'Argentina', 'Argentina'],
    '🇦🇲': ['Армения', 'Armenia', 'Armenia', 'Arménie', 'Armenien', 'Armenia', 'Armênia'],
    '🇦🇼': ['Аруба', 'Aruba', 'Aruba', 'Aruba', 'Aruba', 'Aruba', 'Aruba'],
    '🇦🇺': ['Австралия', 'Australia', 'Australia', 'Australie', 'Australien', 'Australia', 'Austrália'],
    '🇦🇹': ['Австрия', 'Austria', 'Austria', 'Autriche', 'Österreich', 'Austria', 'Áustria'],
    '🇦🇿': ['Азербайджан', 'Azerbaijan', 'Azerbaiyán', 'Azerbaïdjan', 'Aserbaidschan', 'Azerbaigian', 'Azerbaijão'],
    '🇧🇸': ['Багамы', 'Bahamas', 'Bahamas', 'Bahamas', 'Bahamas', 'Bahamas', 'Bahamas'],
    '🇧🇭': ['Бахрейн', 'Bahrain', 'Baréin', 'Bahreïn', 'Bahrain', 'Bahrein', 'Bahrein'],
    '🇧🇩': ['Бангладеш', 'Bangladesh', 'Bangladés', 'Bangladesh', 'Bangladesch', 'Bangladesh', 'Bangladesh'],
    '🇧🇧': ['Барбадос', 'Barbados', 'Barbados', 'Barbade', 'Barbados', 'Barbados', 'Barbados'],
    '🇧🇾': ['Беларусь', 'Belarus', 'Bielorrusia', 'Biélorussie', 'Belarus', 'Bielorussia', 'Bielorrússia'],
    '🇧🇪': ['Бельгия', 'Belgium', 'Bélgica', 'Belgique', 'Belgien', 'Belgio', 'Bélgica'],
    '🇧🇿': ['Белиз', 'Belize', 'Belice', 'Belize', 'Belize', 'Belize', 'Belize'],
    '🇧🇯': ['Бенин', 'Benin', 'Benín', 'Bénin', 'Benin', 'Benin', 'Benin'],
    '🇧🇲': ['Бермуды', 'Bermuda', 'Bermudas', 'Bermudes', 'Bermuda', 'Bermuda', 'Bermudas'],
    '🇧🇹': ['Бутан', 'Bhutan', 'Bután', 'Bhoutan', 'Bhutan', 'Bhutan', 'Butão'],
    '🇧🇴': ['Боливия', 'Bolivia', 'Bolivia', 'Bolivie', 'Bolivien', 'Bolivia', 'Bolívia'],
    '🇧🇦': ['Босния и Герцеговина', 'Bosnia and Herzegovina', 'Bosnia y Herzegovina', 'Bosnie-Herzégovine', 'Bosnien und Herzegowina', 'Bosnia ed Erzegovina', 'Bósnia e Herzegovina'],
    '🇧🇼': ['Ботсвана', 'Botswana', 'Botsuana', 'Botswana', 'Botswana', 'Botswana', 'Botsuana'],
    '🇧🇷': ['Бразилия', 'Brazil', 'Brasil', 'Brésil', 'Brasilien', 'Brasile', 'Brasil'],
    '🇮🇴': ['Британская территория в Индийском океане', 'British Indian Ocean Territory', 'Territorio Británico del Océano Índico', 'Territoire britannique de l\'océan Indien', 'Britisches Territorium im Indischen Ozean', 'Territorio britannico dell\'oceano Indiano', 'Território Britânico do Oceano Índico'],
    '🇻🇬': ['Виргинские острова (Великобритания)', 'British Virgin Islands', 'Islas Vírgenes Británicas', 'Îles Vierges britanniques', 'Britische Jungferninseln', 'Isole Vergini Britanniche', 'Ilhas Virgens Britânicas'],
    '🇧🇳': ['Бруней', 'Brunei', 'Brunéi', 'Brunei', 'Brunei', 'Brunei', 'Brunei'],
    '🇧🇬': ['Болгария', 'Bulgaria', 'Bulgaria', 'Bulgarie', 'Bulgarien', 'Bulgaria', 'Bulgária'],
    '🇧🇫': ['Буркина-Фасо', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso'],
    '🇧🇮': ['Бурунди', 'Burundi', 'Burundi', 'Burundi', 'Burundi', 'Burundi', 'Burundi'],
    '🇰🇭': ['Камбоджа', 'Cambodia', 'Camboya', 'Cambodge', 'Kambodscha', 'Cambogia', 'Camboja'],
    '🇨🇲': ['Камерун', 'Cameroon', 'Camerún', 'Cameroun', 'Kamerun', 'Camerun', 'Camarões'],
    '🇨🇦': ['Канада', 'Canada', 'Canadá', 'Canada', 'Kanada', 'Canada', 'Canadá'],
    '🇮🇨': ['Канарские острова', 'Canary Islands', 'Islas Canarias', 'Îles Canaries', 'Kanarische Inseln', 'Isole Canarie', 'Ilhas Canárias'],
    '🇨🇻': ['Кабо-Верде', 'Cape Verde', 'Cabo Verde', 'Cap-Vert', 'Kap Verde', 'Capo Verde', 'Cabo Verde'],
    '🇧🇶': ['Карибские Нидерланды', 'Caribbean Netherlands', 'Caribe neerlandés', 'Pays-Bas caribéens', 'Karibische Niederlande', 'Paesi Bassi caraibici', 'Países Baixos Caribenhos'],
    '🇰🇾': ['Каймановы острова', 'Cayman Islands', 'Islas Caimán', 'Îles Caïmans', 'Kaimaninseln', 'Isole Cayman', 'Ilhas Cayman'],
    '🇨🇫': ['Центральноафриканская Республика', 'Central African Republic', 'República Centroafricana', 'République centrafricaine', 'Zentralafrikanische Republik', 'Repubblica Centrafricana', 'República Centro-Africana'],
    '🇹🇩': ['Чад', 'Chad', 'Chad', 'Tchad', 'Tschad', 'Ciad', 'Chade'],
    '🇨🇱': ['Чили', 'Chile', 'Chile', 'Chili', 'Chile', 'Cile', 'Chile'],
    '🇨🇳': ['Китай', 'China', 'China', 'Chine', 'China', 'Cina', 'China'],
    '🇨🇽': ['Остров Рождества', 'Christmas Island', 'Isla de Navidad', 'Île Christmas', 'Weihnachtsinsel', 'Isola di Natale', 'Ilha Christmas'],
    '🇨🇨': ['Кокосовые острова', 'Cocos Islands', 'Islas Cocos', 'Îles Cocos', 'Kokosinseln', 'Isole Cocos', 'Ilhas Cocos'],
    '🇨🇴': ['Колумбия', 'Colombia', 'Colombia', 'Colombie', 'Kolumbien', 'Colombia', 'Colômbia'],
    '🇰🇲': ['Коморы', 'Comoros', 'Comoras', 'Comores', 'Komoren', 'Comore', 'Comores'],
    '🇨🇬': ['Конго', 'Congo', 'Congo', 'Congo', 'Kongo', 'Congo', 'Congo'],
    '🇨🇩': ['Демократическая Республика Конго', 'Congo (Democratic Republic)', 'Congo (República Democrática)', 'Congo (République démocratique)', 'Kongo (Demokratische Republik)', 'Congo (Repubblica Democratica)', 'Congo (República Democrática)'],
    '🇨🇰': ['Острова Кука', 'Cook Islands', 'Islas Cook', 'Îles Cook', 'Cookinseln', 'Isole Cook', 'Ilhas Cook'],
    '🇨🇷': ['Коста-Рика', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'Costa Rica'],
    '🇭🇷': ['Хорватия', 'Croatia', 'Croacia', 'Croatie', 'Kroatien', 'Croazia', 'Croácia'],
    '🇨🇺': ['Куба', 'Cuba', 'Cuba', 'Cuba', 'Kuba', 'Cuba', 'Cuba'],
    '🇨🇼': ['Кюрасао', 'Curaçao', 'Curazao', 'Curaçao', 'Curaçao', 'Curaçao', 'Curaçao'],
    '🇨🇾': ['Кипр', 'Cyprus', 'Chipre', 'Chypre', 'Zypern', 'Cipro', 'Chipre'],
    '🇨🇿': ['Чехия', 'Czech Republic', 'República Checa', 'République tchèque', 'Tschechien', 'Repubblica Ceca', 'República Tcheca'],
    '🇨🇮': ['Кот-д\'Ивуар', 'Côte d\'Ivoire', 'Costa de Marfil', 'Côte d\'Ivoire', 'Elfenbeinküste', 'Costa d\'Avorio', 'Costa do Marfim'],
    '🇩🇰': ['Дания', 'Denmark', 'Dinamarca', 'Danemark', 'Dänemark', 'Danimarca', 'Dinamarca'],
    '🇩🇯': ['Джибути', 'Djibouti', 'Yibuti', 'Djibouti', 'Dschibuti', 'Gibuti', 'Djibouti'],
    '🇩🇲': ['Доминика', 'Dominica', 'Dominica', 'Dominique', 'Dominica', 'Dominica', 'Dominica'],
    '🇩🇴': ['Доминиканская Республика', 'Dominican Republic', 'República Dominicana', 'République dominicaine', 'Dominikanische Republik', 'Repubblica Dominicana', 'República Dominicana'],
    '🇪🇨': ['Эквадор', 'Ecuador', 'Ecuador', 'Équateur', 'Ecuador', 'Ecuador', 'Equador'],
    '🇪🇬': ['Египет', 'Egypt', 'Egipto', 'Égypte', 'Ägypten', 'Egitto', 'Egito'],
    '🇸🇻': ['Сальвадор', 'El Salvador', 'El Salvador', 'Salvador', 'El Salvador', 'El Salvador', 'El Salvador'],
    '🇬🇶': ['Экваториальная Гвинея', 'Equatorial Guinea', 'Guinea Ecuatorial', 'Guinée équatoriale', 'Äquatorialguinea', 'Guinea Equatoriale', 'Guiné Equatorial'],
    '🇪🇷': ['Эритрея', 'Eritrea', 'Eritrea', 'Érythrée', 'Eritrea', 'Eritrea', 'Eritreia'],
    '🇪🇪': ['Эстония', 'Estonia', 'Estonia', 'Estonie', 'Estland', 'Estonia', 'Estônia'],
    '🇸🇿': ['Эсватини', 'Eswatini', 'Esuatini', 'Eswatini', 'Eswatini', 'Eswatini', 'Essuatíni'],
    '🇪🇹': ['Эфиопия', 'Ethiopia', 'Etiopía', 'Éthiopie', 'Äthiopien', 'Etiopia', 'Etiópia'],
    '🇫🇰': ['Фолклендские острова', 'Falkland Islands', 'Islas Malvinas', 'Îles Malouines', 'Falklandinseln', 'Isole Falkland', 'Ilhas Malvinas'],
    '🇫🇴': ['Фарерские острова', 'Faroe Islands', 'Islas Feroe', 'Îles Féroé', 'Färöer', 'Isole Faroe', 'Ilhas Faroé'],
    '🇫🇯': ['Фиджи', 'Fiji', 'Fiyi', 'Fidji', 'Fidschi', 'Figi', 'Fiji'],
    '🇫🇮': ['Финляндия', 'Finland', 'Finlandia', 'Finlande', 'Finnland', 'Finlandia', 'Finlândia'],
    '🇫🇷': ['Франция', 'France', 'Francia', 'France', 'Frankreich', 'Francia', 'França'],
    '🇬🇫': ['Французская Гвиана', 'French Guiana', 'Guayana Francesa', 'Guyane française', 'Französisch-Guayana', 'Guyana francese', 'Guiana Francesa'],
    '🇵🇫': ['Французская Полинезия', 'French Polynesia', 'Polinesia Francesa', 'Polynésie française', 'Französisch-Polynesien', 'Polinesia francese', 'Polinésia Francesa'],
    '🇹🇫': ['Французские Южные территории', 'French Southern Territories', 'Tierras Australes Francesas', 'Terres australes françaises', 'Französische Süd- und Antarktisgebiete', 'Terre australi francesi', 'Terras Austrais e Antárticas Francesas'],
    '🇬🇦': ['Габон', 'Gabon', 'Gabón', 'Gabon', 'Gabun', 'Gabon', 'Gabão'],
    '🇬🇲': ['Гамбия', 'Gambia', 'Gambia', 'Gambie', 'Gambia', 'Gambia', 'Gâmbia'],
    '🇬🇪': ['Грузия', 'Georgia', 'Georgia', 'Géorgie', 'Georgien', 'Georgia', 'Geórgia'],
    '🇩🇪': ['Германия', 'Germany', 'Alemania', 'Allemagne', 'Deutschland', 'Germania', 'Alemanha'],
    '🇬🇭': ['Гана', 'Ghana', 'Ghana', 'Ghana', 'Ghana', 'Ghana', 'Gana'],
    '🇬🇮': ['Гибралтар', 'Gibraltar', 'Gibraltar', 'Gibraltar', 'Gibraltar', 'Gibraltar', 'Gibraltar'],
    '🇬🇷': ['Греция', 'Greece', 'Grecia', 'Grèce', 'Griechenland', 'Grecia', 'Grécia'],
    '🇬🇱': ['Гренландия', 'Greenland', 'Groenlandia', 'Groenland', 'Grönland', 'Groenlandia', 'Groenlândia'],
    '🇬🇩': ['Гренада', 'Grenada', 'Granada', 'Grenade', 'Grenada', 'Grenada', 'Granada'],
    '🇬🇵': ['Гваделупа', 'Guadeloupe', 'Guadalupe', 'Guadeloupe', 'Guadeloupe', 'Guadeloupe', 'Guadalupe'],
    '🇬🇺': ['Гуам', 'Guam', 'Guam', 'Guam', 'Guam', 'Guam', 'Guam'],
    '🇬🇹': ['Гватемала', 'Guatemala', 'Guatemala', 'Guatemala', 'Guatemala', 'Guatemala', 'Guatemala'],
    '🇬🇬': ['Гернси', 'Guernsey', 'Guernsey', 'Guernesey', 'Guernsey', 'Guernsey', 'Guernsey'],
    '🇬🇳': ['Гвинея', 'Guinea', 'Guinea', 'Guinée', 'Guinea', 'Guinea', 'Guiné'],
    '🇬🇼': ['Гвинея-Бисау', 'Guinea-Bissau', 'Guinea-Bisáu', 'Guinée-Bissau', 'Guinea-Bissau', 'Guinea-Bissau', 'Guiné-Bissau'],
    '🇬🇾': ['Гайана', 'Guyana', 'Guyana', 'Guyana', 'Guyana', 'Guyana', 'Guiana'],
    '🇭🇹': ['Гаити', 'Haiti', 'Haití', 'Haïti', 'Haiti', 'Haiti', 'Haiti'],
    '🇭🇳': ['Гондурас', 'Honduras', 'Honduras', 'Honduras', 'Honduras', 'Honduras', 'Honduras'],
    '🇭🇰': ['Гонконг', 'Hong Kong', 'Hong Kong', 'Hong Kong', 'Hongkong', 'Hong Kong', 'Hong Kong'],
    '🇭🇺': ['Венгрия', 'Hungary', 'Hungría', 'Hongrie', 'Ungarn', 'Ungheria', 'Hungria'],
    '🇮🇸': ['Исландия', 'Iceland', 'Islandia', 'Islande', 'Island', 'Islanda', 'Islândia'],
    '🇮🇳': ['Индия', 'India', 'India', 'Inde', 'Indien', 'India', 'Índia'],
    '🇮🇩': ['Индонезия', 'Indonesia', 'Indonesia', 'Indonésie', 'Indonesien', 'Indonesia', 'Indonésia'],
    '🇮🇷': ['Иран', 'Iran', 'Irán', 'Iran', 'Iran', 'Iran', 'Irã'],
    '🇮🇶': ['Ирак', 'Iraq', 'Irak', 'Irak', 'Irak', 'Iraq', 'Iraque'],
    '🇮🇪': ['Ирландия', 'Ireland', 'Irlanda', 'Irlande', 'Irland', 'Irlanda', 'Irlanda'],
    '🇮🇲': ['Остров Мэн', 'Isle of Man', 'Isla de Man', 'Île de Man', 'Isle of Man', 'Isola di Man', 'Ilha de Man'],
    '🇮🇱': ['Израиль', 'Israel', 'Israel', 'Israël', 'Israel', 'Israele', 'Israel'],
    '🇮🇹': ['Италия', 'Italy', 'Italia', 'Italie', 'Italien', 'Italia', 'Itália'],
    '🇯🇲': ['Ямайка', 'Jamaica', 'Jamaica', 'Jamaïque', 'Jamaika', 'Giamaica', 'Jamaica'],
    '🇯🇵': ['Япония', 'Japan', 'Japón', 'Japon', 'Japan', 'Giappone', 'Japão'],
    '🇯🇪': ['Джерси', 'Jersey', 'Jersey', 'Jersey', 'Jersey', 'Jersey', 'Jersey'],
    '🇯🇴': ['Иордания', 'Jordan', 'Jordania', 'Jordanie', 'Jordanien', 'Giordania', 'Jordânia'],
    '🇰🇿': ['Казахстан', 'Kazakhstan', 'Kazajistán', 'Kazakhstan', 'Kasachstan', 'Kazakistan', 'Cazaquistão'],
    '🇰🇪': ['Кения', 'Kenya', 'Kenia', 'Kenya', 'Kenia', 'Kenya', 'Quênia'],
    '🇰🇮': ['Кирибати', 'Kiribati', 'Kiribati', 'Kiribati', 'Kiribati', 'Kiribati', 'Kiribati'],
    '🇽🇰': ['Косово', 'Kosovo', 'Kosovo', 'Kosovo', 'Kosovo', 'Kosovo', 'Kosovo'],
    '🇰🇼': ['Кувейт', 'Kuwait', 'Kuwait', 'Koweït', 'Kuwait', 'Kuwait', 'Kuwait'],
    '🇰🇬': ['Киргизия', 'Kyrgyzstan', 'Kirguistán', 'Kirghizistan', 'Kirgisistan', 'Kirghizistan', 'Quirguistão'],
    '🇱🇦': ['Лаос', 'Laos', 'Laos', 'Laos', 'Laos', 'Laos', 'Laos'],
    '🇱🇻': ['Латвия', 'Latvia', 'Letonia', 'Lettonie', 'Lettland', 'Lettonia', 'Letônia'],
    '🇱🇧': ['Ливан', 'Lebanon', 'Líbano', 'Liban', 'Libanon', 'Libano', 'Líbano'],
    '🇱🇸': ['Лесото', 'Lesotho', 'Lesoto', 'Lesotho', 'Lesotho', 'Lesotho', 'Lesoto'],
    '🇱🇷': ['Либерия', 'Liberia', 'Liberia', 'Libéria', 'Liberia', 'Liberia', 'Libéria'],
    '🇱🇾': ['Ливия', 'Libya', 'Libia', 'Libye', 'Libyen', 'Libia', 'Líbia'],
    '🇱🇮': ['Лихтенштейн', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein'],
    '🇱🇹': ['Литва', 'Lithuania', 'Lituania', 'Lituanie', 'Litauen', 'Lituania', 'Lituânia'],
    '🇱🇺': ['Люксембург', 'Luxembourg', 'Luxemburgo', 'Luxembourg', 'Luxemburg', 'Lussemburgo', 'Luxemburgo'],
    '🇲🇴': ['Макао', 'Macao', 'Macao', 'Macao', 'Macau', 'Macao', 'Macau'],
    '🇲🇰': ['Северная Македония', 'North Macedonia', 'Macedonia del Norte', 'Macédoine du Nord', 'Nordmazedonien', 'Macedonia del Nord', 'Macedônia do Norte'],
    '🇲🇬': ['Мадагаскар', 'Madagascar', 'Madagascar', 'Madagascar', 'Madagaskar', 'Madagascar', 'Madagáscar'],
    '🇲🇼': ['Малави', 'Malawi', 'Malaui', 'Malawi', 'Malawi', 'Malawi', 'Malawi'],
    '🇲🇾': ['Малайзия', 'Malaysia', 'Malasia', 'Malaisie', 'Malaysia', 'Malaysia', 'Malásia'],
    '🇲🇻': ['Мальдивы', 'Maldives', 'Maldivas', 'Maldives', 'Malediven', 'Maldive', 'Maldivas'],
    '🇲🇱': ['Мали', 'Mali', 'Malí', 'Mali', 'Mali', 'Mali', 'Mali'],
    '🇲🇹': ['Мальта', 'Malta', 'Malta', 'Malte', 'Malta', 'Malta', 'Malta'],
    '🇲🇭': ['Маршалловы острова', 'Marshall Islands', 'Islas Marshall', 'Îles Marshall', 'Marshallinseln', 'Isole Marshall', 'Ilhas Marshall'],
    '🇲🇶': ['Мартиника', 'Martinique', 'Martinica', 'Martinique', 'Martinique', 'Martinica', 'Martinica'],
    '🇲🇷': ['Мавритания', 'Mauritania', 'Mauritania', 'Mauritanie', 'Mauretanien', 'Mauritania', 'Mauritânia'],
    '🇲🇺': ['Маврикий', 'Mauritius', 'Mauricio', 'Maurice', 'Mauritius', 'Mauritius', 'Maurício'],
    '🇾🇹': ['Майотта', 'Mayotte', 'Mayotte', 'Mayotte', 'Mayotte', 'Mayotte', 'Mayotte'],
    '🇲🇽': ['Мексика', 'Mexico', 'México', 'Mexique', 'Mexiko', 'Messico', 'México'],
    '🇫🇲': ['Микронезия', 'Micronesia', 'Micronesia', 'Micronésie', 'Mikronesien', 'Micronesia', 'Micronésia'],
    '🇲🇩': ['Молдова', 'Moldova', 'Moldavia', 'Moldavie', 'Moldawien', 'Moldova', 'Moldávia'],
    '🇲🇨': ['Монако', 'Monaco', 'Mónaco', 'Monaco', 'Monaco', 'Monaco', 'Mónaco'],
    '🇲🇳': ['Монголия', 'Mongolia', 'Mongolia', 'Mongolie', 'Mongolei', 'Mongolia', 'Mongólia'],
    '🇲🇪': ['Черногория', 'Montenegro', 'Montenegro', 'Monténégro', 'Montenegro', 'Montenegro', 'Montenegro'],
    '🇲🇸': ['Монтсеррат', 'Montserrat', 'Montserrat', 'Montserrat', 'Montserrat', 'Montserrat', 'Montserrat'],
    '🇲🇦': ['Марокко', 'Morocco', 'Marruecos', 'Maroc', 'Marokko', 'Marocco', 'Marrocos'],
    '🇲🇿': ['Мозамбик', 'Mozambique', 'Mozambique', 'Mozambique', 'Mosambik', 'Mozambico', 'Moçambique'],
    '🇲🇲': ['Мьянма', 'Myanmar', 'Birmania', 'Myanmar', 'Myanmar', 'Myanmar', 'Mianmar'],
    '🇳🇦': ['Намибия', 'Namibia', 'Namibia', 'Namibie', 'Namibia', 'Namibia', 'Namíbia'],
    '🇳🇷': ['Науру', 'Nauru', 'Nauru', 'Nauru', 'Nauru', 'Nauru', 'Nauru'],
    '🇳🇵': ['Непал', 'Nepal', 'Nepal', 'Népal', 'Nepal', 'Nepal', 'Nepal'],
    '🇳🇱': ['Нидерланды', 'Netherlands', 'Países Bajos', 'Pays-Bas', 'Niederlande', 'Paesi Bassi', 'Países Baixos'],
    '🇳🇨': ['Новая Каледония', 'New Caledonia', 'Nueva Caledonia', 'Nouvelle-Calédonie', 'Neukaledonien', 'Nuova Caledonia', 'Nova Caledônia'],
    '🇳🇿': ['Новая Зеландия', 'New Zealand', 'Nueva Zelanda', 'Nouvelle-Zélande', 'Neuseeland', 'Nuova Zelanda', 'Nova Zelândia'],
    '🇳🇮': ['Никарагуа', 'Nicaragua', 'Nicaragua', 'Nicaragua', 'Nicaragua', 'Nicaragua', 'Nicarágua'],
    '🇳🇪': ['Нигер', 'Niger', 'Níger', 'Niger', 'Niger', 'Niger', 'Níger'],
    '🇳🇬': ['Нигерия', 'Nigeria', 'Nigeria', 'Nigéria', 'Nigeria', 'Nigeria', 'Nigéria'],
    '🇳🇺': ['Ниуэ', 'Niue', 'Niue', 'Niue', 'Niue', 'Niue', 'Niue'],
    '🇳🇫': ['Остров Норфолк', 'Norfolk Island', 'Isla Norfolk', 'Île Norfolk', 'Norfolkinsel', 'Isola Norfolk', 'Ilha Norfolk'],
    '🇰🇵': ['Северная Корея', 'North Korea', 'Corea del Norte', 'Corée du Nord', 'Nordkorea', 'Corea del Nord', 'Coreia do Norte'],
    '🇲🇵': ['Северные Марианские острова', 'Northern Mariana Islands', 'Islas Marianas del Norte', 'Îles Mariannes du Nord', 'Nördliche Marianen', 'Isole Marianne Settentrionali', 'Ilhas Marianas do Norte'],
    '🇳🇴': ['Норвегия', 'Norway', 'Noruega', 'Norvège', 'Norwegen', 'Norvegia', 'Noruega'],
    '🇴🇲': ['Оман', 'Oman', 'Omán', 'Oman', 'Oman', 'Oman', 'Omã'],
    '🇵🇰': ['Пакистан', 'Pakistan', 'Pakistán', 'Pakistan', 'Pakistan', 'Pakistan', 'Paquistão'],
    '🇵🇼': ['Палау', 'Palau', 'Palaos', 'Palaos', 'Palau', 'Palau', 'Palau'],
    '🇵🇸': ['Палестина', 'Palestine', 'Palestina', 'Palestine', 'Palästina', 'Palestina', 'Palestina'],
    '🇵🇦': ['Панама', 'Panama', 'Panamá', 'Panama', 'Panama', 'Panama', 'Panamá'],
    '🇵🇬': ['Папуа — Новая Гвинея', 'Papua New Guinea', 'Papúa Nueva Guinea', 'Papouasie-Nouvelle-Guinée', 'Papua-Neuguinea', 'Papua Nuova Guinea', 'Papua-Nova Guiné'],
    '🇵🇾': ['Парагвай', 'Paraguay', 'Paraguay', 'Paraguay', 'Paraguay', 'Paraguay', 'Paraguai'],
    '🇵🇪': ['Перу', 'Peru', 'Perú', 'Pérou', 'Peru', 'Perù', 'Peru'],
    '🇵🇭': ['Филиппины', 'Philippines', 'Filipinas', 'Philippines', 'Philippinen', 'Filippine', 'Filipinas'],
    '🇵🇳': ['Питкэрн', 'Pitcairn', 'Pitcairn', 'Pitcairn', 'Pitcairn', 'Pitcairn', 'Pitcairn'],
    '🇵🇱': ['Польша', 'Poland', 'Polonia', 'Pologne', 'Polen', 'Polonia', 'Polônia'],
    '🇵🇹': ['Португалия', 'Portugal', 'Portugal', 'Portugal', 'Portugal', 'Portogallo', 'Portugal'],
    '🇵🇷': ['Пуэрто-Рико', 'Puerto Rico', 'Puerto Rico', 'Porto Rico', 'Puerto Rico', 'Porto Rico', 'Porto Rico'],
    '🇶🇦': ['Катар', 'Qatar', 'Catar', 'Qatar', 'Katar', 'Qatar', 'Catar'],
    '🇷🇪': ['Реюньон', 'Réunion', 'Reunión', 'Réunion', 'Réunion', 'Riunione', 'Reunião'],
    '🇷🇴': ['Румыния', 'Romania', 'Rumania', 'Roumanie', 'Rumänien', 'Romania', 'Romênia'],
    '🇷🇺': ['Россия', 'Russia', 'Rusia', 'Russie', 'Russland', 'Russia', 'Rússia'],
    '🇷🇼': ['Руанда', 'Rwanda', 'Ruanda', 'Rwanda', 'Ruanda', 'Ruanda', 'Ruanda'],
    '🇼🇸': ['Самоа', 'Samoa', 'Samoa', 'Samoa', 'Samoa', 'Samoa', 'Samoa'],
    '🇸🇲': ['Сан-Марино', 'San Marino', 'San Marino', 'Saint-Marin', 'San Marino', 'San Marino', 'San Marino'],
    '🇸🇹': ['Сан-Томе и Принсипи', 'São Tomé and Príncipe', 'Santo Tomé y Príncipe', 'Sao Tomé-et-Principe', 'São Tomé und Príncipe', 'São Tomé e Príncipe', 'São Tomé e Príncipe'],
    '🇸🇦': ['Саудовская Аравия', 'Saudi Arabia', 'Arabia Saudita', 'Arabie saoudite', 'Saudi-Arabien', 'Arabia Saudita', 'Arábia Saudita'],
    '🇸🇳': ['Сенегал', 'Senegal', 'Senegal', 'Sénégal', 'Senegal', 'Senegal', 'Senegal'],
    '🇷🇸': ['Сербия', 'Serbia', 'Serbia', 'Serbie', 'Serbien', 'Serbia', 'Sérvia'],
    '🇸🇨': ['Сейшелы', 'Seychelles', 'Seychelles', 'Seychelles', 'Seychellen', 'Seychelles', 'Seicheles'],
    '🇸🇱': ['Сьерра-Леоне', 'Sierra Leone', 'Sierra Leona', 'Sierra Leone', 'Sierra Leone', 'Sierra Leone', 'Serra Leoa'],
    '🇸🇬': ['Сингапур', 'Singapore', 'Singapur', 'Singapour', 'Singapur', 'Singapore', 'Singapura'],
    '🇸🇽': ['Синт-Мартен', 'Sint Maarten', 'Sint Maarten', 'Saint-Martin', 'Sint Maarten', 'Sint Maarten', 'Sint Maarten'],
    '🇸🇰': ['Словакия', 'Slovakia', 'Eslovaquia', 'Slovaquie', 'Slowakei', 'Slovacchia', 'Eslováquia'],
    '🇸🇮': ['Словения', 'Slovenia', 'Eslovenia', 'Slovénie', 'Slowenien', 'Slovenia', 'Eslovênia'],
    '🇸🇧': ['Соломоновы острова', 'Solomon Islands', 'Islas Salomón', 'Îles Salomon', 'Salomonen', 'Isole Salomone', 'Ilhas Salomão'],
    '🇸🇴': ['Сомали', 'Somalia', 'Somalia', 'Somalie', 'Somalia', 'Somalia', 'Somália'],
    '🇿🇦': ['ЮАР', 'South Africa', 'Sudáfrica', 'Afrique du Sud', 'Südafrika', 'Sudafrica', 'África do Sul'],
    '🇬🇸': ['Южная Георгия и Южные Сандвичевы острова', 'South Georgia and the South Sandwich Islands', 'Georgia del Sur y las Islas Sandwich del Sur', 'Géorgie du Sud et les îles Sandwich du Sud', 'Südgeorgien und die Südlichen Sandwichinseln', 'Georgia del Sud e isole Sandwich meridionali', 'Geórgia do Sul e Ilhas Sandwich do Sul'],
    '🇰🇷': ['Южная Корея', 'South Korea', 'Corea del Sur', 'Corée du Sud', 'Südkorea', 'Corea del Sud', 'Coreia do Sul'],
    '🇸🇸': ['Южный Судан', 'South Sudan', 'Sudán del Sur', 'Soudan du Sud', 'Südsudan', 'Sudan del Sud', 'Sudão do Sul'],
    '🇪🇸': ['Испания', 'Spain', 'España', 'Espagne', 'Spanien', 'Spagna', 'Espanha'],
    '🇱🇰': ['Шри-Ланка', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka'],
    '🇧🇱': ['Сен-Бартелеми', 'Saint Barthélemy', 'San Bartolomé', 'Saint-Barthélemy', 'Saint-Barthélemy', 'Saint-Barthélemy', 'São Bartolomeu'],
    '🇸🇭': ['Остров Святой Елены', 'Saint Helena', 'Santa Elena', 'Sainte-Hélène', 'St. Helena', 'Sant\'Elena', 'Santa Helena'],
    '🇰🇳': ['Сент-Китс и Невис', 'Saint Kitts and Nevis', 'San Cristóbal y Nieves', 'Saint-Christophe-et-Niévès', 'St. Kitts und Nevis', 'Saint Kitts e Nevis', 'São Cristóvão e Nevis'],
    '🇱🇨': ['Сент-Люсия', 'Saint Lucia', 'Santa Lucía', 'Sainte-Lucie', 'St. Lucia', 'Santa Lucia', 'Santa Lúcia'],
    '🇵🇲': ['Сен-Пьер и Микелон', 'Saint Pierre and Miquelon', 'San Pedro y Miquelón', 'Saint-Pierre-et-Miquelon', 'Saint-Pierre und Miquelon', 'Saint-Pierre e Miquelon', 'São Pedro e Miquelon'],
    '🇻🇨': ['Сент-Винсент и Гренадины', 'Saint Vincent and the Grenadines', 'San Vicente y las Granadinas', 'Saint-Vincent-et-les Grenadines', 'St. Vincent und die Grenadinen', 'Saint Vincent e Grenadine', 'São Vicente e Granadinas'],
    '🇸🇩': ['Судан', 'Sudan', 'Sudán', 'Soudan', 'Sudan', 'Sudan', 'Sudão'],
    '🇸🇷': ['Суринам', 'Suriname', 'Surinam', 'Suriname', 'Suriname', 'Suriname', 'Suriname'],
    '🇸🇪': ['Швеция', 'Sweden', 'Suecia', 'Suède', 'Schweden', 'Svezia', 'Suécia'],
    '🇨🇭': ['Швейцария', 'Switzerland', 'Suiza', 'Suisse', 'Schweiz', 'Svizzera', 'Suíça'],
    '🇸🇾': ['Сирия', 'Syria', 'Siria', 'Syrie', 'Syrien', 'Siria', 'Síria'],
    '🇹🇼': ['Тайвань', 'Taiwan', 'Taiwán', 'Taïwan', 'Taiwan', 'Taiwan', 'Taiwan'],
    '🇹🇯': ['Таджикистан', 'Tajikistan', 'Tayikistán', 'Tadjikistan', 'Tadschikistan', 'Tagikistan', 'Tajiquistão'],
    '🇹🇿': ['Танзания', 'Tanzania', 'Tanzania', 'Tanzanie', 'Tansania', 'Tanzania', 'Tanzânia'],
    '🇹🇭': ['Таиланд', 'Thailand', 'Tailandia', 'Thaïlande', 'Thailand', 'Thailandia', 'Tailândia'],
    '🇹🇱': ['Восточный Тимор', 'Timor-Leste', 'Timor Oriental', 'Timor oriental', 'Osttimor', 'Timor Est', 'Timor-Leste'],
    '🇹🇬': ['Того', 'Togo', 'Togo', 'Togo', 'Togo', 'Togo', 'Togo'],
    '🇹🇰': ['Токелау', 'Tokelau', 'Tokelau', 'Tokelau', 'Tokelau', 'Tokelau', 'Tokelau'],
    '🇹🇴': ['Тонга', 'Tonga', 'Tonga', 'Tonga', 'Tonga', 'Tonga', 'Tonga'],
    '🇹🇹': ['Тринидад и Тобаго', 'Trinidad and Tobago', 'Trinidad y Tobago', 'Trinité-et-Tobago', 'Trinidad und Tobago', 'Trinidad e Tobago', 'Trinidad e Tobago'],
    '🇹🇳': ['Тунис', 'Tunisia', 'Túnez', 'Tunisie', 'Tunesien', 'Tunisia', 'Tunísia'],
    '🇹🇷': ['Турция', 'Turkey', 'Turquía', 'Turquie', 'Türkei', 'Turchia', 'Turquia'],
    '🇹🇲': ['Туркменистан', 'Turkmenistan', 'Turkmenistán', 'Turkménistan', 'Turkmenistan', 'Turkmenistan', 'Turcomenistão'],
    '🇹🇨': ['Теркс и Кайкос', 'Turks and Caicos Islands', 'Islas Turcas y Caicos', 'Îles Turques-et-Caïques', 'Turks- und Caicosinseln', 'Isole Turks e Caicos', 'Ilhas Turks e Caicos'],
    '🇹🇻': ['Тувалу', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu'],
    '🇺🇬': ['Уганда', 'Uganda', 'Uganda', 'Ouganda', 'Uganda', 'Uganda', 'Uganda'],
    '🇺🇦': ['Украина', 'Ukraine', 'Ucrania', 'Ukraine', 'Ukraine', 'Ucraina', 'Ucrânia'],
    '🇦🇪': ['ОАЭ', 'United Arab Emirates', 'Emiratos Árabes Unidos', 'Émirats arabes unis', 'Vereinigte Arabische Emirate', 'Emirati Arabi Uniti', 'Emirados Árabes Unidos'],
    '🇬🇧': ['Великобритания', 'United Kingdom', 'Reino Unido', 'Royaume-Uni', 'Vereinigtes Königreich', 'Regno Unito', 'Reino Unido'],
    '🇺🇸': ['США', 'United States', 'Estados Unidos', 'États-Unis', 'Vereinigte Staaten', 'Stati Uniti', 'Estados Unidos'],
    '🇺🇾': ['Уругвай', 'Uruguay', 'Uruguay', 'Uruguay', 'Uruguay', 'Uruguay', 'Uruguai'],
    '🇺🇿': ['Узбекистан', 'Uzbekistan', 'Uzbekistán', 'Ouzbékistan', 'Usbekistan', 'Uzbekistan', 'Uzbequistão'],
    '🇻🇺': ['Вануату', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatu'],
    '🇻🇦': ['Ватикан', 'Vatican City', 'Ciudad del Vaticano', 'Cité du Vatican', 'Vatikanstadt', 'Città del Vaticano', 'Cidade do Vaticano'],
    '🇻🇪': ['Венесуэла', 'Venezuela', 'Venezuela', 'Venezuela', 'Venezuela', 'Venezuela', 'Venezuela'],
    '🇻🇳': ['Вьетнам', 'Vietnam', 'Vietnam', 'Viêt Nam', 'Vietnam', 'Vietnam', 'Vietnã'],
    '🇼🇫': ['Уоллис и Футуна', 'Wallis and Futuna', 'Wallis y Futuna', 'Wallis-et-Futuna', 'Wallis und Futuna', 'Wallis e Futuna', 'Wallis e Futuna'],
    '🇪🇭': ['Западная Сахара', 'Western Sahara', 'Sáhara Occidental', 'Sahara occidental', 'Westsahara', 'Sahara Occidentale', 'Saara Ocidental'],
    '🇾🇪': ['Йемен', 'Yemen', 'Yemen', 'Yémen', 'Jemen', 'Yemen', 'Iêmen'],
    '🇿🇲': ['Замбия', 'Zambia', 'Zambia', 'Zambie', 'Sambia', 'Zambia', 'Zâmbia'],
    '🇿🇼': ['Зимбабве', 'Zimbabwe', 'Zimbabue', 'Zimbabwe', 'Simbabwe', 'Zimbabwe', 'Zimbábue'],
  };

  /// Поиск эмодзи по ключевым словам
  static List<String> searchEmojis(String query) {
    if (query.isEmpty) return [];

    final String queryLower = query.toLowerCase();
    final List<String> searchResults = [];

    // Поиск по ключевым словам
    for (final entry in _emojiKeywords.entries) {
      final emoji = entry.key;
      final keywords = entry.value;

      // Проверяем, содержит ли хотя бы одно ключевое слово запрос
      final hasMatch = keywords.any((keyword) =>
          keyword.toLowerCase().contains(queryLower) ||
          queryLower.contains(keyword.toLowerCase()));

      if (hasMatch) {
        searchResults.add(emoji);
      }
    }

    // Также ищем по названию категории
    for (final category in categories) {
      if (category.name.toLowerCase().contains(queryLower)) {
        for (final emoji in category.emojis) {
          if (!searchResults.contains(emoji)) {
            searchResults.add(emoji);
          }
        }
      }
    }

    return searchResults.take(50).toList(); // Максимум 50 результатов
  }
}